// store/slices/clinicalEncounterSlice.ts
import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';

// Types
export interface Symptom {
  id: string;
  name: string;
  severity: number; // 1-10
  duration: string;
  onset: string;
  notes?: string;
}

export interface VitalSigns {
  temperature: number | null;
  bloodPressure: {
    systolic: number | null;
    diastolic: number | null;
  };
  pulse: number | null;
  respiratoryRate: number | null;
  spO2: number | null;
  weight: number | null;
  height: number | null;
  bmi?: number;
  timestamp: string;
}

export interface ClinicalFinding {
  system: string;
  finding: string;
  location?: string;
  notes?: string;
  abnormal: boolean;
}

export interface DiagnosisSuggestion {
  id: string;
  name: string;
  probability: number; // 0-1
  confidence: 'high' | 'medium' | 'low';
  evidence: string[];
  icd10Code?: string;
  treatmentGuidance?: string;
  urgent?: boolean;
}

export interface PrescriptionItem {
  id: string;
  drugId: string;
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  quantity: number;
  instructions: string;
  formularyAvailable: boolean;
  insuranceCovered: boolean;
  warnings?: string[];
}

export interface LabOrder {
  id: string;
  testId: string;
  testName: string;
  priority: 'routine' | 'urgent' | 'stat';
  specimenType: string;
  instructions?: string;
  status: 'pending' | 'in-progress' | 'completed' | 'cancelled';
  result?: string | number;
  orderedAt: string;
  completedAt?: string;
}

export interface DepartmentTransfer {
  fromDepartment: string;
  toDepartment: string;
  reason: string;
  priority: string;
  timestamp: string;
  staffId: string;
}

export interface ClinicalEncounter {
  id: string;
  patientId: string;
  facilityId: string;
  encounterType: 'outpatient' | 'inpatient' | 'emergency';
  status: 'in-progress' | 'completed' | 'cancelled' | 'forwarded';
  chiefComplaint: string;
  symptoms: Symptom[];
  vitalSigns: VitalSigns[];
  clinicalFindings: ClinicalFinding[];
  diagnosis: DiagnosisSuggestion[];
  differentialDiagnosis: DiagnosisSuggestion[];
  prescriptions: PrescriptionItem[];
  labOrders: LabOrder[];
  clinicalNotes: {
    hpi: string;
    assessment: string;
    plan: string;
    autoGenerated: boolean;
    editedBy?: string;
    editedAt?: string;
  };
  departmentTransfers: DepartmentTransfer[];
  billingItems: Array<{
    itemId: string;
    description: string;
    cost: number;
    quantity: number;
    department: string;
    priority?: string;
  }>;
  allergies: Array<{
    allergen: string;
    reaction: string;
    severity: 'mild' | 'moderate' | 'severe';
    documentedAt: string;
  }>;
  currentMedications: Array<{
    name: string;
    dosage: string;
    frequency: string;
    startDate: string;
  }>;
  aiContext: {
    localDiseasePrevalence: Record<string, number>;
    seasonalPatterns: string[];
    patientHistoryContext: string[];
    communityAlerts: string[];
  };
  createdAt: string;
  updatedAt: string;
  attendingClinician: string;
}

interface ClinicalEncounterState {
  currentEncounter: ClinicalEncounter | null;
  encounters: ClinicalEncounter[];
  aiSuggestions: {
    diagnoses: DiagnosisSuggestion[];
    prescriptions: PrescriptionItem[];
    alerts: Array<{
      type: 'allergy' | 'interaction' | 'abnormal' | 'warning';
      message: string;
      severity: 'info' | 'warning' | 'danger';
    }>;
  };
  loading: boolean;
  error: string | null;
  departmentQueues: Record<string, Array<{
    encounterId: string;
    patientId: string;
    patientName: string;
    priority: string;
    task: string;
    arrivalTime: string;
  }>>;
}

// Mock data for AI suggestions
// const mockSymptoms = [
//   'Fever', 'Headache', 'Cough', 'Fatigue', 'Nausea', 'Vomiting', 
//   'Diarrhea', 'Chest Pain', 'Shortness of Breath', 'Joint Pain'
// ];

const mockDiagnoses = [
  { id: 'malaria', name: 'Malaria', icd10Code: 'B54' },
  { id: 'typhoid', name: 'Typhoid Fever', icd10Code: 'A01.0' },
  { id: 'dengue', name: 'Dengue Fever', icd10Code: 'A90' },
  { id: 'pneumonia', name: 'Pneumonia', icd10Code: 'J18.9' },
  { id: 'uti', name: 'Urinary Tract Infection', icd10Code: 'N39.0' },
  { id: 'covid', name: 'COVID-19', icd10Code: 'U07.1' },
];

// Async thunks
export const generateAIDiagnosis = createAsyncThunk(
  'clinicalEncounter/generateAIDiagnosis',
  async (symptoms: Symptom[]) => {
    // Mock AI diagnosis generation
    await new Promise(resolve => setTimeout(resolve, 500));
    
    const suggestions = mockDiagnoses.map(diag => ({
      ...diag,
      probability: Math.random() * 0.8 + 0.2, // 0.2-1.0
      confidence: ['high', 'medium', 'low'][Math.floor(Math.random() * 3)] as 'high' | 'medium' | 'low',
      evidence: symptoms.slice(0, 2).map(s => s.name),
    }));
    
    return suggestions.sort((a, b) => b.probability - a.probability).slice(0, 5);
  }
);

export const checkDrugInteractions = createAsyncThunk(
  'clinicalEncounter/checkDrugInteractions',
  async (payload: { medications: string[]; allergies: string[] }) => {
    // Mock drug interaction check
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const warnings = [];
    if (payload.medications.includes('Ciprofloxacin') && payload.medications.includes('Metformin')) {
      warnings.push({
        type: 'interaction' as const,
        message: 'Ciprofloxacin interacts with Metformin. Increases risk of hypoglycemia.',
        severity: 'danger' as const,
      });
    }
    
    if (payload.allergies.includes('Penicillin') && payload.medications.some(m => m.includes('Penicillin'))) {
      warnings.push({
        type: 'allergy' as const,
        message: 'Patient allergic to Penicillin. Consider alternative antibiotic.',
        severity: 'danger' as const,
      });
    }
    
    return warnings;
  }
);

export const forwardToDepartment = createAsyncThunk(
  'clinicalEncounter/forwardToDepartment',
  async (payload: {
    encounterId: string;
    fromDepartment: string;
    toDepartment: string;
    reason: string;
    priority?: string;
  }) => {
    // Mock API call
    await new Promise(resolve => setTimeout(resolve, 200));
    
    return {
      ...payload,
      timestamp: new Date().toISOString(),
      staffId: 'current-user-id',
    };
  }
);

const initialState: ClinicalEncounterState = {
  currentEncounter: null,
  encounters: [],
  aiSuggestions: {
    diagnoses: [],
    prescriptions: [],
    alerts: [],
  },
  departmentQueues: {
    laboratory: [],
    pharmacy: [],
    radiology: [],
    billing: [],
  },
  loading: false,
  error: null,
};

      // Helper function to create a valid DepartmentTransfer
      const createDepartmentTransfer = (payload: {
        timestamp: string;
        staffId: string;
        encounterId: string;
        fromDepartment: string;
        toDepartment: string;
        reason: string;
        priority?: string;
      }): DepartmentTransfer => ({
        ...payload,
        priority: payload.priority || 'routine',
        // Add any other required fields with defaults
      });

const clinicalEncounterSlice = createSlice({
  name: 'clinicalEncounter',
  initialState,
  reducers: {
    setCurrentEncounter: (state, action: PayloadAction<ClinicalEncounter>) => {
      state.currentEncounter = action.payload;
    },
    
    updateSymptoms: (state, action: PayloadAction<Symptom[]>) => {
      if (state.currentEncounter) {
        state.currentEncounter.symptoms = action.payload;
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    addVitalSigns: (state, action: PayloadAction<VitalSigns>) => {
      if (state.currentEncounter) {
        state.currentEncounter.vitalSigns.push(action.payload);
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    addClinicalFinding: (state, action: PayloadAction<ClinicalFinding>) => {
      if (state.currentEncounter) {
        state.currentEncounter.clinicalFindings.push(action.payload);
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    addPrescription: (state, action: PayloadAction<PrescriptionItem>) => {
      if (state.currentEncounter) {
        state.currentEncounter.prescriptions.push(action.payload);
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    addLabOrder: (state, action: PayloadAction<LabOrder>) => {
      if (state.currentEncounter) {
        state.currentEncounter.labOrders.push(action.payload);
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    updateClinicalNotes: (state, action: PayloadAction<{
      hpi?: string;
      assessment?: string;
      plan?: string;
    }>) => {
      if (state.currentEncounter) {
        state.currentEncounter.clinicalNotes = {
          ...state.currentEncounter.clinicalNotes,
          ...action.payload,
          autoGenerated: false,
          editedBy: 'current-user',
          editedAt: new Date().toISOString(),
        };
        state.currentEncounter.updatedAt = new Date().toISOString();
      }
    },
    
    addToDepartmentQueue: (state, action: PayloadAction<{
      department: string;
      patient: {
        encounterId: string;
        patientId: string;
        patientName: string;
        priority: string;
        task: string;
      };
    }>) => {
      const { department, patient } = action.payload;
      if (!state.departmentQueues[department]) {
        state.departmentQueues[department] = [];
      }
      
      state.departmentQueues[department].push({
        ...patient,
        arrivalTime: new Date().toISOString(),
      });
    },
    
    removeFromDepartmentQueue: (state, action: PayloadAction<{
      department: string;
      encounterId: string;
    }>) => {
      const { department, encounterId } = action.payload;
      if (state.departmentQueues[department]) {
        state.departmentQueues[department] = state.departmentQueues[department].filter(
          item => item.encounterId !== encounterId
        );
      }
    },
    
    clearAISuggestions: (state) => {
      state.aiSuggestions = {
        diagnoses: [],
        prescriptions: [],
        alerts: [],
      };
    },
    
    resetEncounter: (state) => {
      state.currentEncounter = null;
      state.aiSuggestions = {
        diagnoses: [],
        prescriptions: [],
        alerts: [],
      };
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(generateAIDiagnosis.pending, (state) => {
        state.loading = true;
      })
      .addCase(generateAIDiagnosis.fulfilled, (state, action) => {
        state.loading = false;
        state.aiSuggestions.diagnoses = action.payload;
      })
      .addCase(generateAIDiagnosis.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || 'Failed to generate diagnosis';
      })
      .addCase(checkDrugInteractions.fulfilled, (state, action) => {
        state.aiSuggestions.alerts = [
          ...state.aiSuggestions.alerts,
          ...action.payload,
        ];
      })

        // In your reducer
        .addCase(forwardToDepartment.fulfilled, (state, action) => {
          if (state.currentEncounter) {
            const validTransfer = createDepartmentTransfer(action.payload);
            state.currentEncounter.departmentTransfers.push(validTransfer);
            state.currentEncounter.status = 'forwarded';
            state.currentEncounter.updatedAt = new Date().toISOString();
          }
})
  },
});

export const {
  setCurrentEncounter,
  updateSymptoms,
  addVitalSigns,
  addClinicalFinding,
  addPrescription,
  addLabOrder,
  updateClinicalNotes,
  addToDepartmentQueue,
  removeFromDepartmentQueue,
  clearAISuggestions,
  resetEncounter,
} = clinicalEncounterSlice.actions;

export default clinicalEncounterSlice.reducer;