import React from 'react';
import { BRAND_NAME_UCASE } from '../../utils/BrandName';

export interface PatientRegistrationPrintoutProps {
  patientName: string;
  patientNumber: string;
  registrationDate?: string;
}

export const PatientRegistrationPrintout = React.forwardRef<HTMLDivElement, PatientRegistrationPrintoutProps>(({
  patientName,
  patientNumber,
  registrationDate,
}, ref) => {
  const date = registrationDate || new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <>
      <style>{`
        .patient-registration-printout * {
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
      `}</style>
      <div ref={ref} className="patient-registration-printout bg-white text-black">
        <div className="max-w-lg mx-auto p-8 print:p-6">
          <div className="border-2 border-gray-300 rounded-lg overflow-hidden">
            <div className="bg-blue-600 text-white px-6 py-4 text-center"
              style={{ backgroundColor: '#2563eb' }}
            >
              <h1 className="text-2xl font-bold tracking-tight">
                {BRAND_NAME_UCASE}
              </h1>
              <p className="text-blue-100 text-sm mt-1">
                Patient Registration Confirmation
              </p>
            </div>

            <div className="px-6 py-5 space-y-6">
              <div className="text-center">
                <p className="text-xs text-gray-500 uppercase tracking-widest font-semibold mb-1">
                  Date Registered
                </p>
                <p className="text-sm text-gray-700">{date}</p>
              </div>

              <div className="border-t border-gray-200 pt-5">
                <div className="mb-6">
                  <p className="text-xs text-gray-500 uppercase tracking-widest font-semibold mb-2">
                    Patient Name
                  </p>
                  <p className="text-2xl font-bold text-gray-900 border-b-2 border-gray-200 pb-2">
                    {patientName}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-widest font-semibold mb-2">
                    Patient Number
                  </p>
                  <p className="text-xl font-mono font-bold text-blue-700 bg-blue-50 rounded-md px-3 py-2 inline-block border border-blue-200"
                    style={{ backgroundColor: '#eff6ff' }}
                  >
                    {patientNumber}
                  </p>
                </div>
              </div>

              <div className="border-t border-gray-200 pt-4 mt-4">
                <div className="bg-gray-50 rounded-md px-4 py-3 text-center"
                  style={{ backgroundColor: '#f9fafb' }}
                >
                  <p className="text-xs text-gray-600 leading-relaxed">
                    This is your unique patient identifier. Please present this number
                    at all future visits for faster registration and care coordination.
                  </p>
                </div>
              </div>

              <div className="text-center border-t border-gray-200 pt-4">
                <p className="text-[10px] text-gray-400">
                  Generated by {BRAND_NAME_UCASE} Healthcare Information System
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
});

PatientRegistrationPrintout.displayName = 'PatientRegistrationPrintout';
