// src/routes/routeConstants.ts
export const ROUTES = {
  HOME: '/',
  LANDING: '/home',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_SUCCESS: '/reset-password-success',
  TWO_FACTOR_AUTH: '/two-factor-auth',
  PORTAL_SELECTOR: '/portal-selector', 
  PATIENT_PORTAL: '/portal/patient', 
  DASHBOARD: '/dashboard/staff', 
  ROLE_SELECTION: '/role-selection', 
  PATIENT_ONBOARDING: '/patient-onboarding', 
  STAFF_ONBOARDING: '/staff-onboarding', 
  HEALTHCARE_ONBOARDING: '/healthcare-onboarding', 
  STAFF_DASHBOARD: '/staff-dashboard', 
  PATIENT_DASHBOARD: '/dashboard/patient',
} as const;