// src/modules/clinical/types/clinicalEncounterTypes.ts

/**
 * ============================================================================
 * CLINICAL ENCOUNTER TYPE DEFINITIONS
 * ============================================================================
 */

export type ClinicalOperationId = 
  | 'newEncounter' 
  | 'differentialAI' 
  | 'ePrescribing' 
  | 'clinicalNotes' 
  | 'investigations' 
  | 'departmentFlow' 
  | 'billing';

/* Patient & User Types */
export interface Patient {
  id: string;
  name: string;
  age: number;
  gender: 'Male' | 'Female' | 'Other';
  phone: string;
  medicalRecordNumber: string;
  allergies: string[];
  currentMedications: string[];
  medicalHistory: string[];
}

export interface PatientVitals {
  temperature: number;
  bloodPressure: string;
  pulse: number;
  respiratoryRate: number;
  spO2: number;
  weight: number;
  height?: number;
  bmi?: number;
}

export interface Symptom {
  id: string;
  name: string;
  severity: number; // 1-10
  duration: string;
  onset: string;
  notes?: string;
  timestamp: string;
}

/* AI Diagnosis Types */
export interface DifferentialDiagnosis {
  id: string;
  condition: string;
  probability: number; // 0-100%
  confidence: 'high' | 'medium' | 'low';
  evidence: string[];
  suggestedTests: string[];
  contextFactors: ContextFactor[];
  updatedAt: string;
}

export interface ContextFactor {
  type: 'geographic' | 'seasonal' | 'historical' | 'community';
  factor: string;
  weight: number;
  description: string;
}

export interface DiagnosisUpdate {
  timestamp: string;
  trigger: 'symptom_added' | 'vital_changed' | 'finding_added';
  changes: {
    condition: string;
    previousProbability: number;
    newProbability: number;
    reason: string;
  }[];
}

/* Prescription Types */
export interface PrescriptionItem {
  id: string;
  drug: string;
  dosage: string;
  frequency: string;
  duration: string;
  route: string;
  quantity: number;
  warnings: string[];
  interactions: DrugInteraction[];
  formularyAvailable: boolean;
  insuranceCovered: boolean;
  unitPrice: number;
}

export interface DrugInteraction {
  severity: 'critical' | 'major' | 'moderate' | 'minor';
  interactsWith: string;
  description: string;
  alternatives: string[];
}

/* Investigation Types */
export interface InvestigationOrder {
  id: string;
  type: 'lab' | 'radiology' | 'other';
  testName: string;
  priority: 'routine' | 'urgent' | 'stat';
  orderedBy: string;
  orderedAt: string;
  status: 'pending' | 'in-progress' | 'completed' | 'cancelled';
  instructions?: string;
  results?: InvestigationResult;
}

export interface InvestigationResult {
  completedAt: string;
  performedBy: string;
  findings: string;
  isAbnormal: boolean;
  attachments: string[];
}

/* Department & Workflow Types */
export interface DepartmentRoute {
  id: string;
  from: string;
  to: string;
  patientId: string;
  patientName: string;
  priority: 'routine' | 'urgent' | 'emergency';
  status: 'pending' | 'in-progress' | 'completed';
  forwardedBy: string;
  forwardedAt: string;
  receivedBy?: string;
  receivedAt?: string;
  notes?: string;
}

export interface Department {
  id: string;
  name: string;
  queueLength: number;
  averageWaitTime: number;
  availableStaff: number;
  status: 'operational' | 'busy' | 'closed';
}

/* Billing Types */
export interface BillingItem {
  id: string;
  service: string;
  category: 'consultation' | 'medication' | 'test' | 'procedure';
  quantity: number;
  unitPrice: number;
  total: number;
  insuranceCovered: boolean;
  autoGenerated: boolean;
  timestamp: string;
}

export interface BillingSummary {
  subtotal: number;
  insuranceCovered: number;
  discount: number;
  tax: number;
  patientPayable: number;
  total: number;
}

/* Clinical Encounter State */
export interface ClinicalEncounterState {
  // Patient Selection
  selectedPatient: Patient | null;
  isNewPatient: boolean;
  
  // Clinical Data
  chiefComplaint: string;
  symptoms: Symptom[];
  vitals: PatientVitals | null;
  examFindings: string;
  clinicalNotes: string;
  
  // AI Diagnosis
  differentials: DifferentialDiagnosis[];
  diagnosisHistory: DiagnosisUpdate[];
  selectedDiagnosis: string | null;
  aiProcessing: boolean;
  
  // Prescriptions
  prescriptions: PrescriptionItem[];
  
  // Investigations
  investigations: InvestigationOrder[];
  
  // Workflow
  departmentRoutes: DepartmentRoute[];
  currentDepartment: string;
  
  // Billing
  billingItems: BillingItem[];
  
  // UI State
  activeOperation: ClinicalOperationId;
  loading: boolean;
  error: string | null;
  lastSaved: string | null;
}

/* Mock Data Types */
export interface MockDrugFormulary {
  name: string;
  genericName: string;
  category: string;
  available: boolean;
  insurance: boolean;
  unitPrice: number;
  commonDosages: string[];
  commonFrequencies: string[];
}

export interface AvailableTest {
  name: string;
  category: string;
  type: 'lab' | 'radiology';
  turnaroundTime: string;
  price: number;
  requiresPrep: boolean;
  prepInstructions?: string;
}