/**
 * ============================================================================
 * STREAMLINED STAFF ONBOARDING - MINIMAL DATA COLLECTION
 * ============================================================================
 * 
 * DESIGN PHILOSOPHY: Streamlined staff onboarding with professional focus
 * 
 * DATA COLLECTION:
 * - professional_title (string)
 * - employment_status (string)
 * - employment_type (string) - only shown when status is "employed"
 * 
 * BACKEND INTEGRATION:
 * - Staff ID generated by backend after submission
 * - Clean payload structure matching API expectations
 * - Proper loading, success, and error state handling
 * - Toast notifications for user feedback
 */

import React, { useState, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  User, 
  Briefcase,
  Badge,
  Check,
  ArrowRight,
  Sun,
  Moon,
  ChevronLeft,
  Hospital,
  BadgeCheck,
  AlertCircle,
  Loader2,
  Shield,
} from 'lucide-react';
import { cn } from '../../../../shared/types/cn';
import { useAppDispatch, useAppSelector } from '../../../../app/store/hooks/useApp';
import { toggleTheme } from '../../../../app/store/slices/uiSlice';
import { ROUTES } from '../../routes/onboardingRouteConstants';
import { useRegisterStaff } from '../../../staff/registration/queries/registerStaffQuery';
import { RegisterStaffRequest } from '../../../staff/registration/queries/registerStaffTypes';

/* ==========================================================================
   TYPE DEFINITIONS
   ========================================================================== */

/**
 * Professional title options
 */
type ProfessionalTitle = 
  | 'Doctor'
  | 'Nurse'
  | 'Pharmacist'
  | 'Therapist'
  | 'Technician'
  | 'Allied Health'
  | 'Administrative Staff'
  | 'Support Staff';

/**
 * Employment status options
 */
type EmploymentStatus = 
  | 'employed'
  | 'suspended'
  | 'unemployed'
  | 'terminated'
  | 'retired'
  | 'credentialing_pending';

/**
 * Employment type options
 */
type EmploymentType = 
  | 'full_time'
  | 'part_time'
  | 'contract'
  | 'locum_tenens'
  | 'volunteer';

/**
 * Form data structure (client-side state)
 */
interface StaffFormData {
  professional_title: ProfessionalTitle | '';
  employment_status: EmploymentStatus | '';
  employment_type: EmploymentType | '';
}

/* ==========================================================================
   DATA CONSTANTS
   ========================================================================== */

const PROFESSIONAL_TITLE_OPTIONS: ProfessionalTitle[] = [
  'Doctor',
  'Nurse',
  'Pharmacist',
  'Therapist',
  'Technician',
  'Allied Health',
  'Administrative Staff',
  'Support Staff'
];

const EMPLOYMENT_STATUS_OPTIONS: EmploymentStatus[] = [
  'employed',
  'suspended',
  'unemployed',
  'terminated',
  'retired',
  'credentialing_pending'
];

const EMPLOYMENT_TYPE_OPTIONS: EmploymentType[] = [
  'full_time',
  'part_time',
  'contract',
  'locum_tenens',
  'volunteer'
];

// Map for display labels
const EMPLOYMENT_STATUS_LABELS: Record<EmploymentStatus, string> = {
  employed: 'Employed',
  suspended: 'Suspended',
  unemployed: 'Unemployed',
  terminated: 'Terminated',
  retired: 'Retired',
  credentialing_pending: 'Credentialing Pending'
};

const EMPLOYMENT_TYPE_LABELS: Record<EmploymentType, string> = {
  full_time: 'Full Time',
  part_time: 'Part Time',
  contract: 'Contract',
  locum_tenens: 'Locum Tenens',
  volunteer: 'Volunteer'
};

/* ==========================================================================
   MAIN COMPONENT
   ========================================================================== */

export const MedicalProfessionalOnboarding: React.FC = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const theme = useAppSelector((state) => state.ui.theme);
  
  // Form state
  const [currentStage, setCurrentStage] = useState<1 | 2>(1);
  const [formData, setFormData] = useState<StaffFormData>({
    professional_title: '',
    employment_status: '',
    employment_type: '',
  });
  
  // Backend mutation hook
  const registerStaffMutation = useRegisterStaff({
    onSuccess: (data) => {
      // Success is handled by the mutation hook (toast notification)
      console.log('Staff registered successfully:', data.data.staff_uuid);
    },
    onError: (error) => {
      // Error is handled by the mutation hook (toast notification)
      console.error('Staff registration failed:', error);
    }
  });

  /* ==========================================================================
     FORM HANDLERS
     ========================================================================== */

  /**
   * Update form fields
   */
  const updateField = useCallback((
    field: keyof StaffFormData, 
    value: string
  ) => {
    setFormData(prev => {
      // If employment status changes and is not "employed", clear employment_type
      if (field === 'employment_status' && value !== 'employed') {
        return {
          ...prev,
          [field]: value,
          employment_type: ''
        };
      }
      
      return {
        ...prev,
        [field]: value
      };
    });
  }, []);

  /* ==========================================================================
     FORM VALIDATION
     ========================================================================== */

  /**
   * Validate Stage 1: Professional Information
   */
  const isStage1Valid = useMemo(() => {
    return formData.professional_title !== '' && 
           formData.employment_status !== '';
  }, [formData.professional_title, formData.employment_status]);

  /**
   * Validate Stage 2: Employment Details
   */
  const isStage2Valid = useMemo(() => {
    // If employment_status is "employed", employment_type is required
    if (formData.employment_status === 'employed') {
      return formData.employment_type !== '';
    }
    // For other statuses, employment_type is not required
    return true;
  }, [formData.employment_status, formData.employment_type]);

  /**
   * Overall form validation
   */
  const isFormComplete = useMemo(() => {
    return isStage1Valid && isStage2Valid;
  }, [isStage1Valid, isStage2Valid]);

  /**
   * Should show employment type field
   */
  const shouldShowEmploymentType = useMemo(() => {
    return formData.employment_status === 'employed';
  }, [formData.employment_status]);

  /* ==========================================================================
     FORM SUBMISSION
     ========================================================================== */

  /**
   * Prepare clean payload for backend submission
   */
  const { user } = useAppSelector((state) => state.auth);

  const prepareSubmissionPayload = useCallback((): RegisterStaffRequest => {
    if (!user?.id) {
      throw new Error('User ID is required to register a staff member');
    }
    
    const payload: RegisterStaffRequest = {
      professional_title: formData.professional_title as ProfessionalTitle,
      employment_status: formData.employment_status as EmploymentStatus,
      user_id: user.id,
    };
    
    // Only include employment_type if employment_status is "employed"
    if (formData.employment_status === 'employed' && formData.employment_type) {
      payload.employment_type = formData.employment_type as EmploymentType;
    }
    
    return payload;
  }, [formData, user]);

  /**
   * Submit form to backend using React Query mutation
   */
  const handleSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate form completeness
    if (!isFormComplete) {
      return;
    }

    // Prepare and submit payload
    const payload = prepareSubmissionPayload();
    registerStaffMutation.mutate(payload);
  }, [isFormComplete, prepareSubmissionPayload, registerStaffMutation]);

  /**
   * Navigate to dashboard after successful registration
   */
  const handleContinueToDashboard = useCallback(() => {
    if (!registerStaffMutation.data?.data) {
      return;
    }

    const staffData = registerStaffMutation.data.data;
    
    navigate(ROUTES.STAFF_DASHBOARD, {
      state: {
        staffID: staffData.staff_uuid,
        staffUUID: staffData.staff_uuid,
        isNewStaff: true,
        professionalTitle: staffData.professional_title,
        employmentStatus: staffData.employment_status,
        employmentType: staffData.employment_type,
      }
    });
  }, [registerStaffMutation.data, navigate]);

  /* ==========================================================================
     COMPUTED STATE
     ========================================================================== */

  const isSubmitting = registerStaffMutation.isPending;
  const isComplete = registerStaffMutation.isSuccess;
  const registeredStaffID = registerStaffMutation.data?.data?.staff_uuid || '';

  /* ==========================================================================
     RENDER COMPONENTS
     ========================================================================== */

  /**
   * Progress Indicator
   */
  const renderProgress = () => {
    const progress = currentStage === 1 ? 50 : 100;
    
    return (
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className={cn(
              "text-2xl font-bold",
              theme === 'dark' ? "text-white" : "text-slate-900"
            )}>
              {currentStage === 1 ? "Professional Information" : "Employment Details"}
            </h2>
            <p className={cn(
              "text-sm mt-1",
              theme === 'dark' ? "text-slate-400" : "text-slate-600"
            )}>
              Step {currentStage} of 2
            </p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-blue-600">
              {progress}%
            </div>
          </div>
        </div>

        <div className="relative h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden">
          <motion.div
            className="absolute top-0 left-0 h-full rounded-full bg-gradient-to-r from-blue-600 to-emerald-600"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.5, ease: "easeOut" }}
          />
        </div>
      </div>
    );
  };

  /**
   * Reusable Select Field Component
   */
  const renderSelect = (
    value: string,
    onChange: (value: string) => void,
    label: string,
    icon?: React.ReactNode,
    options: Array<{ value: string; label: string }> = []
  ) => {
    const isEmpty = !value;
    
    return (
      <div className="space-y-2">
        <label className={cn(
          "block text-sm font-medium",
          theme === 'dark' ? "text-white" : "text-slate-900"
        )}>
          {label}
        </label>
        
        <div className="relative">
          {icon && (
            <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 z-10">
              {icon}
            </div>
          )}
          
          <select
            value={value}
            onChange={(e) => onChange(e.target.value)}
            className={cn(
              "w-full px-4 py-3 rounded-xl border-2 appearance-none",
              "focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all",
              theme === 'dark'
                ? "bg-slate-800 border-slate-700 text-white"
                : "bg-white border-slate-200 text-slate-900",
              icon ? "pl-11" : "pl-4",
              !isEmpty && "border-emerald-500"
            )}
          >
            <option value="">Select {label.toLowerCase()}</option>
            {options.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
          
          {!isEmpty && (
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              className="absolute right-3 top-1/2 -translate-y-1/2 z-10"
            >
              <Check className="w-5 h-5 text-emerald-500" />
            </motion.div>
          )}
        </div>
      </div>
    );
  };

  /**
   * Form Sections
   */
  const renderFormSection = () => (
    <form onSubmit={handleSubmit} className="space-y-6">
      <AnimatePresence mode="wait">
        {/* Stage 1: Professional Information */}
        {currentStage === 1 && (
          <motion.div 
            key="stage-1"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="space-y-6"
          >
            {renderSelect(
              formData.professional_title,
              (value) => updateField('professional_title', value),
              'Professional Title',
              <User className="w-5 h-5" />,
              PROFESSIONAL_TITLE_OPTIONS.map(title => ({
                value: title,
                label: title
              }))
            )}
            
            {renderSelect(
              formData.employment_status,
              (value) => updateField('employment_status', value),
              'Employment Status',
              <Briefcase className="w-5 h-5" />,
              EMPLOYMENT_STATUS_OPTIONS.map(status => ({
                value: status,
                label: EMPLOYMENT_STATUS_LABELS[status]
              }))
            )}

            <div className={cn(
              "p-4 rounded-xl border-2 flex items-start gap-3",
              theme === 'dark' 
                ? "bg-blue-900/20 border-blue-800" 
                : "bg-blue-50 border-blue-200"
            )}>
              <Shield className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className={cn(
                  "font-semibold mb-1",
                  theme === 'dark' ? "text-blue-300" : "text-blue-900"
                )}>
                  Professional Setup
                </p>
                <p className={cn(
                  "text-xs",
                  theme === 'dark' ? "text-blue-400" : "text-blue-700"
                )}>
                  Your professional information is encrypted and HIPAA-compliant. 
                  This setup enables access to staff-specific features and permissions.
                </p>
              </div>
            </div>
          </motion.div>
        )}

        {/* Stage 2: Employment Details */}
        {currentStage === 2 && (
          <motion.div 
            key="stage-2"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="space-y-6"
          >
            <div className={cn(
              "p-4 rounded-xl border-2",
              theme === 'dark' 
                ? "bg-slate-800/50 border-slate-700" 
                : "bg-slate-50 border-slate-200"
            )}>
              <h3 className={cn(
                "text-lg font-semibold mb-1 flex items-center gap-2",
                theme === 'dark' ? "text-white" : "text-slate-900"
              )}>
                <Briefcase className="w-5 h-5 text-blue-500" />
                Employment Details
              </h3>
              <p className={cn(
                "text-xs",
                theme === 'dark' ? "text-slate-400" : "text-slate-600"
              )}>
                Additional details required for {formData.employment_status === 'employed' ? 'active employment' : 'current status'}
              </p>
            </div>

            {/* Show employment type only if status is "employed" */}
            {shouldShowEmploymentType && (
              renderSelect(
                formData.employment_type,
                (value) => updateField('employment_type', value),
                'Employment Type',
                <Badge className="w-5 h-5" />,
                EMPLOYMENT_TYPE_OPTIONS.map(type => ({
                  value: type,
                  label: EMPLOYMENT_TYPE_LABELS[type]
                }))
              )
            )}

            {/* Status-specific informational messages */}
            {formData.employment_status !== 'employed' && (
              <div className={cn(
                "p-4 rounded-xl border-2",
                theme === 'dark' 
                  ? "bg-yellow-900/20 border-yellow-800" 
                  : "bg-yellow-50 border-yellow-200"
              )}>
                <h4 className={cn(
                  "font-semibold mb-1 flex items-center gap-2",
                  theme === 'dark' ? "text-yellow-300" : "text-yellow-900"
                )}>
                  <AlertCircle className="w-5 h-5" />
                  Status Note
                </h4>
                <p className={cn(
                  "text-sm",
                  theme === 'dark' ? "text-yellow-400" : "text-yellow-700"
                )}>
                  {formData.employment_status === 'credentialing_pending' 
                    ? 'Your account will have limited access until credentials are verified.'
                    : formData.employment_status === 'suspended'
                    ? 'Your account access may be restricted. Contact HR for details.'
                    : formData.employment_status === 'terminated'
                    ? 'This registration is for record-keeping purposes only.'
                    : 'Your account will be configured based on your employment status.'}
                </p>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Navigation */}
      <div className="flex justify-between pt-6">
        {currentStage > 1 ? (
          <button
            type="button"
            onClick={() => setCurrentStage(1)}
            disabled={isSubmitting}
            className={cn(
              "flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-all",
              theme === 'dark'
                ? "border-2 border-slate-700 text-slate-300 hover:bg-slate-800"
                : "border-2 border-slate-300 text-slate-700 hover:bg-slate-50",
              isSubmitting && "opacity-50 cursor-not-allowed"
            )}
          >
            <ChevronLeft className="w-5 h-5" />
            Back
          </button>
        ) : (
          <div />
        )}
        
        {currentStage < 2 ? (
          <button
            type="button"
            disabled={!isStage1Valid}
            onClick={() => setCurrentStage(2)}
            className={cn(
              "ml-auto flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all",
              isStage1Valid
                ? "bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700"
                : "bg-gray-200 dark:bg-gray-700 text-gray-500 cursor-not-allowed"
            )}
          >
            Continue
            <ArrowRight className="w-5 h-5" />
          </button>
        ) : (
          <button
            type="submit"
            disabled={!isFormComplete || isSubmitting}
            className={cn(
              "ml-auto flex items-center gap-2 px-8 py-3 rounded-xl font-bold transition-all",
              isFormComplete && !isSubmitting
                ? "bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700"
                : "bg-gray-200 dark:bg-gray-700 text-gray-500 cursor-not-allowed"
            )}
          >
            {isSubmitting ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Submitting...
              </>
            ) : (
              <>
                <BadgeCheck className="w-5 h-5" />
                Complete Registration
              </>
            )}
          </button>
        )}
      </div>
    </form>
  );

  /**
   * Success Screen - Display Backend-Generated Staff ID
   */
  const renderSuccessScreen = () => (
    <div className="space-y-8 text-center">
      <motion.div
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: "spring", duration: 0.6 }}
      >
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 mb-6 shadow-xl">
          <BadgeCheck className="w-10 h-10 text-white" />
        </div>
      </motion.div>

      <div>
        <h2 className={cn(
          "text-3xl font-bold mb-3",
          theme === 'dark' ? "text-white" : "text-slate-900"
        )}>
          Registration Complete!
        </h2>
        <p className={cn(
          "text-lg",
          theme === 'dark' ? "text-slate-400" : "text-slate-600"
        )}>
          Your staff account has been created successfully
        </p>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className={cn(
          "rounded-2xl border-2 p-8",
          theme === 'dark'
            ? "bg-slate-800 border-slate-700"
            : "bg-white border-slate-200"
        )}
      >
        <div className="mb-6">
          <p
            className={cn(
              "text-sm font-medium mb-2",
              theme === 'dark' ? "text-slate-400" : "text-slate-600"
            )}
          >
            Your Staff ID
          </p>

          <div className="text-3xl md:text-4xl font-black tracking-tight bg-gradient-to-r from-blue-600 to-emerald-600 bg-clip-text text-transparent break-all">
            {registeredStaffID}
          </div>

          <p
            className={cn(
              "text-xs mt-2",
              theme === 'dark' ? "text-slate-500" : "text-slate-500"
            )}
          >
            This unique identifier will be used for system access and professional documentation.
          </p>
        </div>

        {/* Professional Details Summary */}
        <div className={cn(
          "p-4 rounded-xl border mb-6 text-left",
          theme === 'dark'
            ? "bg-slate-900/50 border-slate-700"
            : "bg-slate-50 border-slate-200"
        )}>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className={cn(
                "text-xs font-medium mb-1",
                theme === 'dark' ? "text-slate-500" : "text-slate-500"
              )}>
                Professional Title
              </p>
              <p className={cn(
                "font-semibold",
                theme === 'dark' ? "text-white" : "text-slate-900"
              )}>
                {formData.professional_title}
              </p>
            </div>
            <div>
              <p className={cn(
                "text-xs font-medium mb-1",
                theme === 'dark' ? "text-slate-500" : "text-slate-500"
              )}>
                Status
              </p>
              <div className="flex items-center gap-2">
                <div className={cn(
                  "w-2 h-2 rounded-full ",
                  formData.employment_status === 'employed' 
                    ? "bg-emerald-500 animate-pulse"
                    : formData.employment_status === 'credentialing_pending'
                    ? "bg-yellow-500 animate-pulse"
                    : "bg-red-500"
                )} />
                <span className="font-semibold text-blue-500">
                  {EMPLOYMENT_STATUS_LABELS[formData.employment_status as EmploymentStatus]}
                </span>
              </div>
            </div>
          </div>
          
          {formData.employment_type && (
            <div className="mt-3">
              <p className={cn(
                "text-xs font-medium mb-1",
                theme === 'dark' ? "text-slate-500" : "text-slate-500"
              )}>
                Employment Type
              </p>
              <p className={cn(
                "font-semibold",
                theme === 'dark' ? "text-white" : "text-slate-900"
              )}>
                {EMPLOYMENT_TYPE_LABELS[formData.employment_type as EmploymentType]}
              </p>
            </div>
          )}
        </div>

        <button
          onClick={handleContinueToDashboard}
          className="w-full flex items-center justify-center gap-3 px-8 py-4 rounded-xl font-bold text-lg bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700 transition-all"
        >
          Continue to Staff Portal
          <ArrowRight className="w-6 h-6" />
        </button>
      </motion.div>
    </div>
  );

  /* ==========================================================================
     MAIN RENDER
     ========================================================================== */

  return (
    <div className={cn(
      "min-h-screen flex flex-col relative",
      theme === 'dark' 
        ? "bg-gradient-to-br from-slate-950 via-gray-900 to-slate-950" 
        : "bg-gradient-to-br from-slate-50 via-white to-blue-50/40"
    )}>
      {/* Decorative Background */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className={cn(
          "absolute -top-32 -right-32 w-[600px] h-[600px] rounded-full blur-3xl",
          theme === 'dark' ? "bg-blue-600/20" : "bg-blue-400/15"
        )} />
        <div className={cn(
          "absolute -bottom-32 -left-32 w-[600px] h-[600px] rounded-full blur-3xl",
          theme === 'dark' ? "bg-emerald-600/20" : "bg-emerald-400/15"
        )} />
      </div>

      {/* Header */}
      <header className={cn(
        "sticky top-0 z-50 border-b backdrop-blur-xl",
        theme === 'dark' 
          ? "bg-slate-900/75 border-slate-800/60" 
          : "bg-white/75 border-slate-200/60"
      )}>
        <nav className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-blue-600 to-emerald-600 flex items-center justify-center shadow-lg">
                <Hospital className="w-6 h-6 text-white" />
              </div>
              <div>
                <div className="text-xl font-bold tracking-tight bg-gradient-to-r from-blue-600 to-emerald-600 bg-clip-text text-transparent">
                  CustoCare AI
                </div>
                <div className={cn(
                  "text-[11px] font-semibold tracking-wide uppercase",
                  theme === 'dark' ? "text-slate-500" : "text-slate-500"
                )}>
                  Staff Registration
                </div>
              </div>
            </div>

            <button
              onClick={() => dispatch(toggleTheme())}
              className={cn(
                "p-3 rounded-xl transition-all border-2",
                theme === 'dark'
                  ? 'bg-slate-800/60 border-slate-700/60 text-amber-300'
                  : 'bg-slate-100 border-slate-200 text-slate-600'
              )}
            >
              {theme === 'dark' ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          </div>
        </nav>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex items-center justify-center px-4 py-12 relative z-10">
        <div className="w-full max-w-2xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={cn(
              "rounded-3xl border-2 p-8 backdrop-blur-xl shadow-2xl",
              theme === 'dark'
                ? "bg-slate-800/85 border-slate-700/60"
                : "bg-white/90 border-slate-200/60"
            )}
          >
            {!isComplete ? (
              <>
                {renderProgress()}
                {renderFormSection()}
              </>
            ) : (
              renderSuccessScreen()
            )}
          </motion.div>
        </div>
      </main>

      {/* Footer */}
      <footer className={cn(
        "py-6 px-4 border-t backdrop-blur-xl",
        theme === 'dark' 
          ? "bg-slate-900/60 border-slate-800/60" 
          : "bg-white/60 border-slate-200/60"
      )}>
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Shield className="w-4 h-4 text-emerald-500" />
            <span className={cn(
              "text-sm font-semibold",
              theme === 'dark' ? "text-slate-300" : "text-slate-700"
            )}>
              HIPAA Compliant • 256-bit Encryption
            </span>
          </div>
          <p className={cn(
            "text-xs",
            theme === 'dark' ? "text-slate-500" : "text-slate-500"
          )}>
            © 2024 CustoCare AI. All professional information is encrypted and protected.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default MedicalProfessionalOnboarding;