import {
  ACCOUNT_ROUTES,
  BILLING_ROUTES,
  CLINICAL_ROUTES,
  CUSTOCARE_HUB_ROUTES,
  LABORATORY_ROUTES,
  MEDICAL_RECORDS_ROUTES,
  NURSING_ROUTES,
  // PATIENT_PORTAL_ROUTES,
  PHARMACY_ROUTES,
  ROUTES,
} from '../../../../../app/routes/routeConstants';
import { ADMIN_ROUTES, ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES, ADMINISTRATION_FACILITY_SETTINGS_ROUTES } from '../../../../../app/routes/constants/administration.paths';
import { PLATFORM_ADMIN_ROUTES } from '../../../../../app/routes/constants/platform-administration.paths';
import type { SearchableModule } from '../StatusBarTypes';

export const allModules: SearchableModule[] = [
  // Patient Portal
  // { id: 'patient-dashboard', label: 'My Health', route: PATIENT_PORTAL_ROUTES.OVERVIEW, description: 'Patient overview, health summary, and personal care dashboard.', moduleCode: 'patient_dashboard', keywords: ['my health', 'patient dashboard', 'health overview', 'personal health', 'vitals', 'conditions', 'allergies', 'where is my health summary'], category: 'Patient Portal' },
  // { id: 'patient-health', label: 'Health', route: PATIENT_PORTAL_ROUTES.HEALTH, description: 'View health summary, vitals, conditions, and allergies.', moduleCode: 'patient_dashboard', keywords: ['health', 'health summary', 'vitals', 'conditions', 'allergies', 'current health'], category: 'Patient Portal' },
  // { id: 'patient-records', label: 'Patient Records', route: PATIENT_PORTAL_ROUTES.RECORDS, description: 'Access, request, and manage personal records.', moduleCode: 'patient_dashboard', keywords: ['records', 'medical records', 'download records', 'share records', 'request records', 'history'], category: 'Patient Portal' },
  // { id: 'patient-test-results', label: 'Test Results', route: PATIENT_PORTAL_ROUTES.TEST_RESULTS, description: 'Track test and laboratory results over time.', moduleCode: 'patient_dashboard', keywords: ['test results', 'lab results', 'compare results', 'result history', 'explain results'], category: 'Patient Portal' },
  // { id: 'patient-appointments', label: 'Appointments', route: PATIENT_PORTAL_ROUTES.APPOINTMENTS, description: 'Manage upcoming and past appointments.', moduleCode: 'patient_dashboard', keywords: ['appointments', 'schedule', 'book appointment', 'cancel appointment', 'upcoming', 'past visits'], category: 'Patient Portal' },
  // { id: 'patient-medications', label: 'Medications', route: PATIENT_PORTAL_ROUTES.MEDICATIONS, description: 'Review current medications and refill requests.', moduleCode: 'patient_dashboard', keywords: ['medications', 'current meds', 'refill', 'interaction check', 'prescriptions'], category: 'Patient Portal' },

  // Staff Portal
  { id: 'staff-dashboard', label: 'Staff Portal', route: ROUTES.STAFF_DASHBOARD, description: 'Staff workspace entry and capability selection.', moduleCode: 'staff_dashboard', keywords: ['staff portal', 'staff dashboard', 'workspace', 'employee', 'switch workspace'], category: 'Administration' },

  // Custocare Hub
  { id: 'hub-learning-center', label: 'Custocare Hub — Learning Center', route: CUSTOCARE_HUB_ROUTES.LEARNING_CENTER, description: 'Tutorials, training paths, and getting started guides.', moduleCode: 'custocare_hub', keywords: ['custocare hub', 'learning center', 'training', 'tutorials', 'getting started', 'hub training'], category: 'Custocare Hub' },
  { id: 'hub-community', label: 'Custocare Hub — Community', route: CUSTOCARE_HUB_ROUTES.COMMUNITY, description: 'Discussions, feature ideas, product updates, and community posts.', moduleCode: 'custocare_hub', keywords: ['custocare hub community', 'hub discussions', 'community posts', 'feature ideas hub', 'product updates hub'], category: 'Custocare Hub' },
  { id: 'hub-support-center', label: 'Custocare Hub — Support Center', route: CUSTOCARE_HUB_ROUTES.SUPPORT_CENTER, description: 'Help articles, FAQs, and support tickets.', moduleCode: 'custocare_hub', keywords: ['custocare hub support', 'help center', 'open ticket', 'hub faq', 'search help'], category: 'Custocare Hub' },
  { id: 'hub-feedback-requests', label: 'Custocare Hub — Feedback & requests', route: CUSTOCARE_HUB_ROUTES.FEEDBACK_REQUESTS, description: 'Submit feedback, request features, and track status.', moduleCode: 'custocare_hub', keywords: ['feature request', 'product feedback', 'vote feature', 'hub feedback'], category: 'Custocare Hub' },

  // Medical Records
  { id: 'mr-intelligence', label: 'Patient Intelligence', route: MEDICAL_RECORDS_ROUTES.OVERVIEW, description: 'Patient analytics, demographics, flow, and clinical performance.', moduleCode: 'medical_records', keywords: ['patient intelligence', 'medical records overview', 'patient analytics', 'clinical dashboard', 'care flow', 'demographics', 'patient statistics'], category: 'Clinical' },
  { id: 'mr-search', label: 'Medical Records - Search Patient', route: MEDICAL_RECORDS_ROUTES.PATIENTS_SEARCH, description: 'Find existing patients quickly.', moduleCode: 'medical_records', keywords: ['search patient', 'find patient', 'lookup patient', 'patient search'], category: 'Clinical' },
  { id: 'mr-register', label: 'Medical Records - Register Patient', route: MEDICAL_RECORDS_ROUTES.PATIENTS_REGISTER, description: 'Create a new patient profile.', moduleCode: 'medical_records', keywords: ['register patient', 'new patient', 'create patient', 'intake'], category: 'Clinical' },
  { id: 'mr-queue', label: 'Medical Records - Patient Queue', route: MEDICAL_RECORDS_ROUTES.PATIENT_QUEUE, description: 'Manage waiting patient queue and triage flow.', moduleCode: 'medical_records', keywords: ['patient queue', 'waiting line', 'triage queue', 'who is waiting'], category: 'Clinical' },
  { id: 'mr-walkin', label: 'Medical Records - Walk-In', route: MEDICAL_RECORDS_ROUTES.WALKIN_PATIENT, description: 'Capture unscheduled walk-in encounters.', moduleCode: 'medical_records', keywords: ['walk in', 'unscheduled patient', 'urgent walkin', 'drop in'], category: 'Clinical' },
  { id: 'mr-patient-records', label: 'Patient Encounter Hub - Patient Info', route: MEDICAL_RECORDS_ROUTES.PATIENT_RECORDS, description: 'Current visit details and medical history view.', moduleCode: 'medical_records', keywords: ['patient info', 'encounter hub', 'medical history', 'current visit', 'records preview'], category: 'Clinical' },
  { id: 'mr-clinical-care', label: 'Patient Encounter Hub - Clinical Care', route: MEDICAL_RECORDS_ROUTES.CLINICAL_CARE, description: 'Encounter forms and care activities.', moduleCode: 'medical_records', keywords: ['clinical care', 'encounter forms', 'care workspace', 'doctor forms'], category: 'Clinical' },
  { id: 'mr-forward', label: 'Patient Encounter Hub - Forward Patient', route: MEDICAL_RECORDS_ROUTES.FORWARD_PATIENT, description: 'Forward patient to the next service point.', moduleCode: 'medical_records', keywords: ['forward patient', 'transfer patient', 'refer patient', 'send patient'], category: 'Clinical' },
  { id: 'mr-visit-status', label: 'Patient Encounter Hub - Visit Status', route: MEDICAL_RECORDS_ROUTES.VISIT_STATUS, description: 'Update and monitor visit progression.', moduleCode: 'medical_records', keywords: ['visit status', 'encounter status', 'close visit', 'patient progress'], category: 'Clinical' },
  { id: 'mr-complaints', label: 'Patient Encounter Hub - Complaints', route: MEDICAL_RECORDS_ROUTES.GET_COMPLAINTS, description: 'Capture presenting complaints and symptoms.', moduleCode: 'medical_records', keywords: ['complaints', 'chief complaint', 'symptoms', 'presenting issues'], category: 'Clinical' },
  { id: 'mr-billing-space', label: 'Patient Encounter Hub - Billing Space', route: MEDICAL_RECORDS_ROUTES.PATIENT_BILLING_SPACE, description: 'Visit billing and charge capture.', moduleCode: 'medical_records', keywords: ['billing space', 'charge entry', 'patient charges', 'visit billing'], category: 'Clinical' },
  { id: 'mr-billing-review', label: 'Medical Records - Billing Reconciliation', route: MEDICAL_RECORDS_ROUTES.BILLING_CYCLE_REVIEW, description: 'Billing cycle review and reconciliation.', moduleCode: 'medical_records', keywords: ['billing cycle review', 'reconciliation', 'invoice matching', 'payment review'], category: 'Clinical' },
  { id: 'mr-billing-stats', label: 'Medical Records - Revenue Stats', route: MEDICAL_RECORDS_ROUTES.BILLING_STATS, description: 'Revenue metrics and billing performance.', moduleCode: 'medical_records', keywords: ['revenue stats', 'billing analytics', 'collections', 'financial stats'], category: 'Clinical' },

  // Clinical Module
  { id: 'clinical-intelligence', label: 'Clinical Intelligence', route: CLINICAL_ROUTES.OVERVIEW, description: 'Clinical analytics and consultation intelligence.', moduleCode: 'clinical', keywords: ['clinical intelligence', 'clinical overview', 'doctor dashboard', 'consultation analytics'], category: 'Clinical' },
  { id: 'clinical-search', label: 'Clinical - Search Patient', route: CLINICAL_ROUTES.PATIENTS_SEARCH, description: 'Search patient for clinical workflow.', moduleCode: 'clinical', keywords: ['clinical search', 'search patient clinical', 'find patient clinical'], category: 'Clinical' },
  { id: 'clinical-register', label: 'Clinical - Register Patient', route: CLINICAL_ROUTES.PATIENTS_REGISTER, description: 'Register patient in clinical intake.', moduleCode: 'clinical', keywords: ['clinical register', 'new clinical patient', 'clinical intake'], category: 'Clinical' },
  { id: 'clinical-queue', label: 'Clinical - Patient Queue', route: CLINICAL_ROUTES.PATIENT_QUEUE, description: 'Queue for clinical consultations.', moduleCode: 'clinical', keywords: ['clinical queue', 'doctor queue', 'consult queue'], category: 'Clinical' },
  { id: 'clinical-walkin', label: 'Clinical - Walk-In', route: CLINICAL_ROUTES.WALKIN_PATIENT, description: 'Handle walk-ins in clinical module.', moduleCode: 'clinical', keywords: ['clinical walk in', 'unscheduled consultation'], category: 'Clinical' },
  { id: 'clinical-visit-status', label: 'Clinical - Visit Status', route: CLINICAL_ROUTES.VISIT_STATUS, description: 'Update status of clinical encounters.', moduleCode: 'clinical', keywords: ['clinical visit status', 'encounter status clinical'], category: 'Clinical' },
  { id: 'clinical-forward', label: 'Clinical - Forward Patient', route: CLINICAL_ROUTES.FORWARD_PATIENT, description: 'Forward patient from clinical workflow.', moduleCode: 'clinical', keywords: ['forward clinical patient', 'clinical referral', 'send patient next'], category: 'Clinical' },

  // Nursing Module
  { id: 'nursing-intelligence', label: 'Nursing Intelligence', route: NURSING_ROUTES.OVERVIEW, description: 'Nursing operations and care intelligence dashboard.', moduleCode: 'nursing', keywords: ['nursing intelligence', 'nursing dashboard', 'care metrics', 'nurse performance'], category: 'Clinical' },
  { id: 'nursing-search-patient', label: 'Nursing - Search Patient', route: NURSING_ROUTES.WARDS_PATIENTS_SEARCH_PATIENT, description: 'Search patients for ward and nursing assignment.', moduleCode: 'nursing', keywords: ['nursing search', 'ward patient search', 'find ward patient'], category: 'Clinical' },
  { id: 'nursing-my-ward', label: 'Nursing - My Ward Patients', route: NURSING_ROUTES.WARDS_PATIENTS_MY_WARD_PATIENTS, description: 'Patients currently assigned to your ward.', moduleCode: 'nursing', keywords: ['my ward patients', 'assigned ward patients', 'ward census'], category: 'Clinical' },
  { id: 'nursing-new-unassigned', label: 'Nursing - New Patients Unassigned', route: NURSING_ROUTES.WARDS_PATIENTS_NEW_PATIENTS_UNASSIGNED, description: 'Unassigned ward patient queue.', moduleCode: 'nursing', keywords: ['new unassigned patients', 'ward queue', 'assign patient'], category: 'Clinical' },
  { id: 'nursing-patient-info', label: 'Nursing Encounter - Patient Info', route: NURSING_ROUTES.NURSING_ENCOUNTER_PATIENT_INFO, description: 'Patient context view in nursing encounter.', moduleCode: 'nursing', keywords: ['nursing patient info', 'encounter patient context', 'patient details nursing'], category: 'Clinical' },
  { id: 'nursing-ward-bed', label: 'Nursing Encounter - Ward Bed', route: NURSING_ROUTES.NURSING_ENCOUNTER_WARD_BED, description: 'Bed assignment and ward bed actions.', moduleCode: 'nursing', keywords: ['ward bed', 'bed allocation', 'assign bed'], category: 'Clinical' },
  { id: 'nursing-medication-schedule', label: 'Medication Schedule', route: NURSING_ROUTES.MEDICATION_TREATMENT_MEDICATION_SCHEDULE, description: 'Medication administration schedule.', moduleCode: 'nursing', keywords: ['medication schedule', 'drug timing', 'med rounds'], category: 'Clinical' },
  { id: 'nursing-administer-medication', label: 'Administer Medication', route: NURSING_ROUTES.MEDICATION_TREATMENT_ADMINISTER_MEDICATION, description: 'Record administered medication doses.', moduleCode: 'nursing', keywords: ['administer medication', 'give dose', 'dose administration', 'mar'], category: 'Clinical' },
  { id: 'nursing-shift-handover', label: 'Shift Handover', route: NURSING_ROUTES.TASKS_SHIFTS_SHIFT_HANDOVER, description: 'Shift handover reporting and transition.', moduleCode: 'nursing', keywords: ['shift handover', 'handoff', 'nurse handover'], category: 'Clinical' },
  { id: 'nursing-my-tasks', label: 'My Nursing Tasks', route: NURSING_ROUTES.TASKS_SHIFTS_MY_TASKS, description: 'Nursing tasks and follow-ups.', moduleCode: 'nursing', keywords: ['my tasks', 'nursing tasks', 'to do', 'task list'], category: 'Clinical' },

  // Laboratory Module
  { id: 'lab-intelligence', label: 'Laboratory Intelligence', route: LABORATORY_ROUTES.OVERVIEW, description: 'Laboratory dashboard for requests, results, and billing signals.', moduleCode: 'laboratory', keywords: ['laboratory intelligence', 'lab overview', 'diagnostics dashboard', 'lab analytics'], category: 'Clinical' },
  { id: 'lab-queue', label: 'Laboratory Queue', route: LABORATORY_ROUTES.PATIENT_QUEUE, description: 'Visits queued for laboratory workflow.', moduleCode: 'laboratory', keywords: ['laboratory queue', 'lab queue', 'diagnostic queue', 'waiting lab'], category: 'Clinical' },
  { id: 'lab-request', label: 'Lab Request Workflow', route: LABORATORY_ROUTES.ACTION_CENTER_REQUEST, description: 'Open lab request forms in encounter context.', moduleCode: 'laboratory', keywords: ['lab request', 'order test', 'request diagnostics', 'open form'], category: 'Clinical' },
  { id: 'lab-results', label: 'Lab Results Workflow', route: LABORATORY_ROUTES.ACTION_CENTER_RESULTS, description: 'Capture and verify laboratory results.', moduleCode: 'laboratory', keywords: ['lab results', 'enter results', 'verify result', 'result capture'], category: 'Clinical' },
  { id: 'lab-patient-info', label: 'Lab Encounter - Patient Info', route: LABORATORY_ROUTES.ACTION_CENTER_PATIENT_INFO, description: 'Current visit and history for laboratory context.', moduleCode: 'laboratory', keywords: ['lab patient info', 'current visit lab', 'history for lab scientist'], category: 'Clinical' },
  { id: 'lab-billing-space', label: 'Lab Billing Space', route: LABORATORY_ROUTES.ACTION_CENTER_BILLING, description: 'Billing actions within laboratory encounter.', moduleCode: 'laboratory', keywords: ['lab billing', 'diagnostic charges', 'bill lab service'], category: 'Clinical' },
  { id: 'lab-catalog-services', label: 'Laboratory Service Catalog', route: LABORATORY_ROUTES.CATALOG_SERVICES, description: 'Laboratory service catalog configuration.', moduleCode: 'laboratory', keywords: ['lab catalog', 'service catalog lab', 'diagnostic services'], category: 'Clinical' },
  { id: 'lab-catalog-inventory', label: 'Laboratory Inventory Catalog', route: LABORATORY_ROUTES.CATALOG_INVENTORY, description: 'Laboratory inventory and reagent items.', moduleCode: 'laboratory', keywords: ['lab inventory', 'reagents', 'consumables', 'inventory catalog'], category: 'Clinical' },
  { id: 'lab-receipts', label: 'Laboratory Receipts', route: LABORATORY_ROUTES.RECEIPTS, description: 'Laboratory receipts and billing review.', moduleCode: 'laboratory', keywords: ['lab receipts', 'diagnostic receipts', 'lab payments'], category: 'Clinical' },

  // Pharmacy Module
  { id: 'pharmacy-intelligence', label: 'Pharmacy Intelligence', route: PHARMACY_ROUTES.OVERVIEW, description: 'Pharmacy overview and dispensing analytics.', moduleCode: 'pharmacy', keywords: ['pharmacy intelligence', 'pharmacy dashboard', 'dispensing analytics', 'medication trends'], category: 'Clinical' },
  { id: 'pharmacy-queue', label: 'Pharmacy Queue', route: PHARMACY_ROUTES.PATIENT_QUEUE, description: 'Queue for dispensing and pharmacy workflow.', moduleCode: 'pharmacy', keywords: ['pharmacy queue', 'dispensing queue', 'patients for pharmacy'], category: 'Clinical' },
  { id: 'pharmacy-dispensing', label: 'Dispense Medication', route: PHARMACY_ROUTES.ACTION_CENTER_DISPENSING, description: 'Medication dispensing workspace.', moduleCode: 'pharmacy', keywords: ['dispense medication', 'dispensing', 'issue drugs', 'fill prescription'], category: 'Clinical' },
  { id: 'pharmacy-rx-search', label: 'Prescription Search', route: PHARMACY_ROUTES.ACTION_CENTER_PRESCRIPTION_SEARCH, description: 'Search prescriptions in active visit context.', moduleCode: 'pharmacy', keywords: ['prescription search', 'find prescription', 'rx search'], category: 'Clinical' },
  { id: 'pharmacy-rx-review', label: 'Prescription Review', route: PHARMACY_ROUTES.ACTION_CENTER_PRESCRIPTION_REVIEW, description: 'Review prescriptions before dispensing.', moduleCode: 'pharmacy', keywords: ['prescription review', 'verify rx', 'approve prescription'], category: 'Clinical' },
  { id: 'pharmacy-inventory', label: 'Pharmacy Inventory', route: PHARMACY_ROUTES.INVENTORY, description: 'Inventory and medication stock management.', moduleCode: 'pharmacy', keywords: ['pharmacy inventory', 'medication stock', 'drug inventory'], category: 'Clinical' },
  { id: 'pharmacy-receipts', label: 'Pharmacy Receipts', route: PHARMACY_ROUTES.RECEIPTS, description: 'Pharmacy receipts and billing records.', moduleCode: 'pharmacy', keywords: ['pharmacy receipts', 'dispensing payments', 'pharmacy billing'], category: 'Clinical' },

  // Billing Module
  { id: 'billing-intelligence', label: 'Financial Intelligence', route: BILLING_ROUTES.INTELLIGENCE, description: 'Billing analytics, revenue trends, and financial operations.', moduleCode: 'billing', keywords: ['financial intelligence', 'billing intelligence', 'revenue stats', 'collections', 'finance dashboard'], category: 'Finance' },
  { id: 'billing-queue', label: 'Billing Queue', route: BILLING_ROUTES.PATIENT_QUEUE, description: 'Visits waiting for billing workflow.', moduleCode: 'billing', keywords: ['billing queue', 'charge queue', 'ready for billing'], category: 'Finance' },
  { id: 'billing-encounter', label: 'Billing Encounter', route: BILLING_ROUTES.BILLING_SPACE, description: 'Charge entry and payment actions for selected visit.', moduleCode: 'billing', keywords: ['billing encounter', 'charge entry', 'proceed to payment', 'complete payment'], category: 'Finance' },
  { id: 'billing-reconciliation', label: 'Receipts & Reconciliation', route: BILLING_ROUTES.RECEIPTS_RECONCILIATION, description: 'Receipts management and reconciliation.', moduleCode: 'billing', keywords: ['receipts', 'reconciliation', 'payment matching', 'cash reconciliation'], category: 'Finance' },
  { id: 'billing-invoices', label: 'Invoices', route: BILLING_ROUTES.INVOICES, description: 'Invoice records and billing documentation.', moduleCode: 'billing', keywords: ['invoices', 'invoice search', 'billing documents', 'statement'], category: 'Finance' },
  { id: 'billing-forward', label: 'Billing - Forward Patient', route: BILLING_ROUTES.FORWARD_PATIENT, description: 'Forward patient from billing encounter.', moduleCode: 'billing', keywords: ['forward from billing', 'transfer billing patient'], category: 'Finance' },
  { id: 'billing-status', label: 'Billing - Visit Status', route: BILLING_ROUTES.VISIT_STATUS, description: 'Update visit status in billing flow.', moduleCode: 'billing', keywords: ['billing visit status', 'close billing visit', 'status update'], category: 'Finance' },

  // Administration
  { id: 'admin-overview', label: 'Facility Intelligence', route: ADMIN_ROUTES.OVERVIEW, description: 'Administrative intelligence across workforce, capacity, and performance.', moduleCode: 'administration', keywords: ['facility intelligence', 'admin dashboard', 'operations analytics', 'management insights'], category: 'Administration' },
  { id: 'admin-team', label: 'Workforce Administration', route: ADMIN_ROUTES.TEAM, description: 'Manage staff, invitations, and role assignments.', moduleCode: 'administration', keywords: ['team management', 'staff management', 'invite staff', 'roles permissions'], category: 'Administration' },
  { id: 'admin-facility-setup', label: 'Clinical Departments', route: ADMIN_ROUTES.FACILITY_SETUP, description: 'Configure departments and facility structure.', moduleCode: 'administration', keywords: ['facility setup', 'departments', 'unit setup', 'organization structure'], category: 'Administration' },
  { id: 'admin-service-catalog', label: 'Clinical & Billing Services', route: ADMIN_ROUTES.SERVICE_CATALOG, description: 'Manage services, procedures, and pricing versions.', moduleCode: 'administration', keywords: ['service catalog', 'procedure pricing', 'billable service', 'service setup'], category: 'Administration' },
  { id: 'admin-inventory', label: 'Supply & Inventory Management', route: ADMIN_ROUTES.INVENTORY, description: 'Inventory stock and supply controls.', moduleCode: 'administration', keywords: ['inventory', 'supplies', 'stock levels', 'item management'], category: 'Administration' },
  { id: 'admin-billing-review', label: 'Billing Cycle Review', route: ADMIN_ROUTES.BILLING_CYCLE_BILLING_REVIEW, description: 'Review billing cycles and payment periods.', moduleCode: 'administration', keywords: ['billing cycle review', 'cycle validation', 'billing period'], category: 'Administration' },
  { id: 'admin-billing-stats', label: 'Billing Cycle Revenue Statistics', route: ADMIN_ROUTES.BILLING_CYCLE_REVENUE_STATS, description: 'Billing cycle revenue and performance metrics.', moduleCode: 'administration', keywords: ['billing revenue stats', 'cycle revenue', 'payment analytics'], category: 'Administration' },
  { id: 'admin-clinical-rooms', label: 'Clinical Rooms', route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.CLINICAL_ROOMS, description: 'Manage consultation and clinical rooms.', moduleCode: 'administration', keywords: ['clinical rooms', 'room management', 'consult rooms'], category: 'Administration' },
  { id: 'admin-ward-management', label: 'Ward Management', route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.WARD_MANAGEMENT, description: 'Ward setup and bed operations.', moduleCode: 'administration', keywords: ['ward management', 'bed allocation', 'inpatient wards'], category: 'Administration' },
  { id: 'admin-facility-zones', label: 'Facility Zones', route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.FACILITY_ZONES, description: 'Define operational zones and sections.', moduleCode: 'administration', keywords: ['facility zones', 'zones', 'wings', 'layout'], category: 'Administration' },
  { id: 'admin-space-allocation', label: 'Space Allocation', route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.SPACE_ALLOCATION, description: 'Assign staff to rooms and clinical spaces.', moduleCode: 'administration', keywords: ['space allocation', 'staff room assignment', 'assign space'], category: 'Administration' },
  { id: 'admin-facility-identity', label: 'Facility Identity', route: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.FACILITY_IDENTITY, description: 'Facility profile, identity, and branding.', moduleCode: 'administration', keywords: ['facility identity', 'facility profile', 'branding settings'], category: 'Administration' },
  { id: 'admin-operational-policies', label: 'Operational Policies', route: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.OPERATIONAL_POLICIES, description: 'Operational and policy configuration.', moduleCode: 'administration', keywords: ['operational policies', 'policy settings', 'rules and procedures'], category: 'Administration' },

  // Platform Administration
  { id: 'platform-admin-facilities', label: 'Platform Administration - Facilities', route: PLATFORM_ADMIN_ROUTES.FACILITIES, description: 'Manage facilities across the platform.', moduleCode: 'platform_administration', keywords: ['platform facilities', 'global facilities', 'tenant facilities', 'facility governance'], category: 'Platform Administration', requiredCapability: 'super_admin' },
  { id: 'platform-admin-users', label: 'Platform Administration - Users', route: PLATFORM_ADMIN_ROUTES.USERS, description: 'Manage global users and access.', moduleCode: 'platform_administration', keywords: ['platform users', 'global users', 'access management', 'user governance'], category: 'Platform Administration', requiredCapability: 'super_admin' },
  { id: 'platform-admin-plans', label: 'Platform Plans & Subscriptions', route: PLATFORM_ADMIN_ROUTES.FACILITIES_PLANS, description: 'Platform-wide plans and subscription controls.', moduleCode: 'platform_administration', keywords: ['platform plans', 'subscriptions', 'global pricing', 'plan management'], category: 'Platform Administration', requiredCapability: 'super_admin' },
  { id: 'platform-admin-hub-support-tickets', label: 'Hub support tickets', route: PLATFORM_ADMIN_ROUTES.HUB_SUPPORT_TICKETS, description: 'Review and resolve Custocare Hub support tickets.', moduleCode: 'platform_administration', keywords: ['hub tickets', 'support tickets', 'custocare hub support', 'helpdesk'], category: 'Platform Administration', requiredCapability: 'super_admin' },
  { id: 'platform-admin-hub-product-updates', label: 'Hub product updates', route: PLATFORM_ADMIN_ROUTES.HUB_PRODUCT_UPDATES, description: 'Publish read-only product announcements for Custocare Hub Community.', moduleCode: 'platform_administration', keywords: ['hub product updates', 'custocare announcements', 'community product updates'], category: 'Platform Administration', requiredCapability: 'super_admin' },

  // Account
  { id: 'account-profile', label: 'My Profile', route: ACCOUNT_ROUTES.SETTINGS_PROFILE, description: 'Update account identity and profile details.', moduleCode: 'account', keywords: ['my profile', 'account profile', 'personal details', 'update profile'], category: 'Account' },
  { id: 'account-security', label: 'Account Security', route: ACCOUNT_ROUTES.SETTINGS_SECURITY, description: 'Security settings, password, and MFA.', moduleCode: 'account', keywords: ['account security', 'password', '2fa', 'mfa', 'login security'], category: 'Account' },
  { id: 'account-preferences', label: 'User Preferences', route: ACCOUNT_ROUTES.SETTINGS_PREFERENCES, description: 'Application preferences and personalization.', moduleCode: 'account', keywords: ['preferences', 'user settings', 'theme', 'language', 'notifications'], category: 'Account' },
  { id: 'account-invitations', label: 'Invitations', route: ACCOUNT_ROUTES.INVITATIONS, description: 'Manage invitations and pending joins.', moduleCode: 'account', keywords: ['invitations', 'invites', 'join request', 'facility invite'], category: 'Account' },
  { id: 'account-message-center', label: 'Message Center', route: ACCOUNT_ROUTES.MESSAGES, description: 'Inbox and communication center.', moduleCode: 'account', keywords: ['message center', 'inbox', 'messages', 'communication'], category: 'Account' },
  { id: 'account-compose-message', label: 'Compose Message', route: ACCOUNT_ROUTES.MESSAGES_COMPOSE, description: 'Compose and send a new message.', moduleCode: 'account', keywords: ['compose message', 'new message', 'write message', 'send message'], category: 'Account' },
  { id: 'account-message-inbox', label: 'Message Inbox', route: ACCOUNT_ROUTES.MESSAGES_INBOX, description: 'View received messages.', moduleCode: 'account', keywords: ['message inbox', 'received messages', 'unread messages'], category: 'Account' },
  { id: 'account-message-sent', label: 'Sent Messages', route: ACCOUNT_ROUTES.MESSAGES_SENT, description: 'View sent messages.', moduleCode: 'account', keywords: ['sent messages', 'outbox', 'sent items'], category: 'Account' },
  { id: 'account-message-draft', label: 'Draft Messages', route: ACCOUNT_ROUTES.MESSAGES_DRAFT, description: 'View and continue message drafts.', moduleCode: 'account', keywords: ['draft messages', 'saved drafts', 'unsent messages'], category: 'Account' },
  { id: 'account-message-trash', label: 'Trash', route: ACCOUNT_ROUTES.MESSAGES_TRASH, description: 'Deleted messages bin.', moduleCode: 'account', keywords: ['trash', 'deleted messages', 'message bin', 'recycle bin'], category: 'Account' },

  // Common shortcuts
  { id: 'shortcut-medical-records-root', label: 'Medical Records', route: MEDICAL_RECORDS_ROUTES.OVERVIEW, description: 'Jump to Medical Records intelligence page.', moduleCode: 'medical_records', keywords: ['medical records', 'front desk', 'reception'], category: 'Clinical' },
  { id: 'shortcut-clinical-root', label: 'Clinical', route: CLINICAL_ROUTES.OVERVIEW, description: 'Jump to Clinical intelligence page.', moduleCode: 'clinical', keywords: ['clinical', 'doctor workspace', 'consultation'], category: 'Clinical' },
  { id: 'shortcut-nursing-root', label: 'Nursing', route: NURSING_ROUTES.OVERVIEW, description: 'Jump to Nursing intelligence page.', moduleCode: 'nursing', keywords: ['nursing', 'nurse workspace', 'ward care'], category: 'Clinical' },
  { id: 'shortcut-lab-root', label: 'Laboratory', route: LABORATORY_ROUTES.OVERVIEW, description: 'Jump to Laboratory intelligence page.', moduleCode: 'laboratory', keywords: ['lab', 'laboratory', 'diagnostics'], category: 'Clinical' },
  { id: 'shortcut-pharmacy-root', label: 'Pharmacy', route: PHARMACY_ROUTES.OVERVIEW, description: 'Jump to Pharmacy intelligence page.', moduleCode: 'pharmacy', keywords: ['pharmacy', 'dispensing', 'medications'], category: 'Clinical' },
  { id: 'shortcut-billing-root', label: 'Billing', route: BILLING_ROUTES.INTELLIGENCE, description: 'Jump to Financial intelligence page.', moduleCode: 'billing', keywords: ['billing', 'finance', 'financial intelligence'], category: 'Finance' },
  { id: 'shortcut-admin-root', label: 'Administration', route: ADMIN_ROUTES.OVERVIEW, description: 'Jump to Facility intelligence page.', moduleCode: 'administration', keywords: ['administration', 'facility governance', 'admin overview'], category: 'Administration' },
  { id: 'shortcut-custocare-hub-root', label: 'Custocare Hub', route: CUSTOCARE_HUB_ROUTES.LEARNING_CENTER, description: 'Jump to the Custocare Hub learning workspace.', moduleCode: 'custocare_hub', keywords: ['custocare hub', 'hub', 'help', 'documentation hub'], category: 'Custocare Hub' },
];
