// search/searchModules.ts
// NOTE: import paths are one level deeper than the original SearchBar.tsx
import { ACCOUNT_ROUTES, BILLING_ROUTES, ROUTES }       from '../../../../../app/routes/routeConstants';
import { PLATFORM_ADMIN_ROUTES} from '../../../../../app/routes/constants/platform-administration.paths';
import { MEDICAL_RECORDS_ROUTES }        from '../../../../../app/routes/routeConstants';
import {
  ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES,
  ADMINISTRATION_FACILITY_SETTINGS_ROUTES,
  // ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES,
} from '../../../../../app/routes/constants/administration.paths';
import { ADMIN_ROUTES } from '../../../../../app/routes/constants/administration.paths';
import type { SearchableModule } from '../StatusBarTypes';

export const allModules: SearchableModule[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // PATIENT PORTAL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'patient-dashboard',
    label: 'My Health',
    route: ROUTES.PATIENT_DASHBOARD,
    description: 'Personal health overview',
    moduleCode: 'patient_dashboard',
    keywords: ['health', 'patient', 'dashboard', 'overview', 'personal'],
    category: 'Patient Portal',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAFF PORTAL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'staff-dashboard',
    label: 'Staff Portal',
    route: ROUTES.STAFF_DASHBOARD,
    description: 'Staff workspace',
    moduleCode: 'staff_dashboard',
    keywords: ['staff', 'portal', 'dashboard', 'workspace', 'employee'],
    category: 'Administration',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CLINICAL — Front Desk / Medical Records
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'medical-records',
    label: 'Medical Records ',
    route: ROUTES.MEDICAL_RECORDS,
    description: 'Medical Records, Patient Registration & workflows',
    moduleCode: 'medical_records',
    keywords: ['front desk', 'reception', 'records', 'medical', 'registration', 'patient intake'],
    category: 'Clinical',
  },
 {
  id: 'medical-records-dashboard',
  label: 'Patient Intelligence',
  route: MEDICAL_RECORDS_ROUTES.OVERVIEW,
  description: 'Executive-grade visibility into patient volume, care flow, retention, demographics, visit composition, and revenue performance.',
  moduleCode: 'medical_records',
  keywords: [
    // Core
    'patient analytics',
    'patient intelligence',
    'clinical intelligence',
    
    // Metrics
    'patient volume',
    'care flow', 
    'patient retention',
    'demographics',
    'visit composition',
    'revenue performance',
    
    // Search terms
    'medical records dashboard',
    'patient statistics',
    'healthcare analytics',
    'clinical dashboard'
  ],
  category: 'Clinical',
},
  {
    id: 'patient-search',
    label: 'Search Patient',
    route: MEDICAL_RECORDS_ROUTES.PATIENTS_SEARCH,
    description: 'Search and find patient records',
    moduleCode: 'medical_records',
    keywords: ['search', 'find', 'patient', 'records', 'lookup'],
    category: 'Clinical',
  },
  {
    id: 'new-patient',
    label: 'New Patient Registration',
    route: MEDICAL_RECORDS_ROUTES.PATIENTS_REGISTER,
    description: 'Register a new patient',
    moduleCode: 'medical_records',
    keywords: ['new', 'register', 'create', 'patient', 'enroll'],
    category: 'Clinical',
  },
  {
    id: 'patient-queue',
    label: 'Patient Queue',
    route: MEDICAL_RECORDS_ROUTES.PATIENT_QUEUE,
    description: 'Manage patient waiting queue',
    moduleCode: 'medical_records',
    keywords: ['queue', 'waiting', 'line', 'patients', 'triage'],
    category: 'Clinical',
  },
  {
    id: 'walk-in-patient',
    label: 'Walk-In Patient',
    route: MEDICAL_RECORDS_ROUTES.WALKIN_PATIENT,
    description: 'Process walk-in patient registration',
    moduleCode: 'medical_records',
    keywords: ['walk-in', 'urgent', 'unscheduled', 'drop-in'],
    category: 'Clinical',
  },
  {
    id: 'get-complaints',
    label: 'Get Complaints',
    route: MEDICAL_RECORDS_ROUTES.GET_COMPLAINTS,
    description: 'Record patient complaints and symptoms',
    moduleCode: 'medical_records',
    keywords: ['complaints', 'symptoms', 'issues', 'problems', 'chief complaint'],
    category: 'Clinical',
  },
  {
    id: 'forward-patient',
    label: 'Forward Patient',
    route: MEDICAL_RECORDS_ROUTES.FORWARD_PATIENT,
    description: 'Forward patient to another department',
    moduleCode: 'medical_records',
    keywords: ['forward', 'transfer', 'refer', 'department', 'specialist'],
    category: 'Clinical',
  },
  {
    id: 'patient-billing-space',
    label: 'Patient Billing Space',
    route: MEDICAL_RECORDS_ROUTES.PATIENT_BILLING_SPACE,
    description: 'View patient billing and payment information',
    moduleCode: 'medical_records',
    keywords: ['billing', 'payment', 'invoice', 'charges', 'patient billing'],
    category: 'Clinical',
  },
  {
    id: 'visit-status',
    label: 'Visit Status',
    route: MEDICAL_RECORDS_ROUTES.VISIT_STATUS,
    description: 'Track and update patient visit status',
    moduleCode: 'medical_records',
    keywords: ['visit', 'status', 'tracking', 'encounter', 'appointment'],
    category: 'Clinical',
  },
 {
    id: 'medical-records-billing-cycle-review',
    label: 'Billing & Reconciliation',
    route: MEDICAL_RECORDS_ROUTES.BILLING_CYCLE_REVIEW,
    description: 'Review patient billing cycles, reconcile medical records with billing data, and track payment status',
    moduleCode: 'medical_records',
    keywords: ['billing cycle', 'reconciliation', 'payment status', 'billing review', 'claim reconciliation', 'invoice matching'],
    category: 'Clinical',
  },
  // {
  //   id: 'nursing-care',
  //   label: 'Nursing Care',
  //   route: ROUTES.NURSING,
  //   description: 'Vitals & ward care',
  //   moduleCode: 'nursing',
  //   keywords: ['nursing', 'vitals', 'ward', 'care', 'nurse'],
  //   category: 'Clinical',
  // },
  // {
  //   id: 'clinical',
  //   label: 'Clinical Workspace',
  //   route: ROUTES.CLINICAL,
  //   description: 'Doctor Consultation & diagnosis',
  //   moduleCode: 'clinical',
  //   keywords: ['clinical', 'doctor', 'consultation', 'diagnosis', 'physician'],
  //   category: 'Clinical',
  // },
  // {
  //   id: 'laboratory',
  //   label: 'Laboratory',
  //   route: ROUTES.LABORATORY,
  //   description: 'Lab tests, results & specimens',
  //   moduleCode: 'laboratory',
  //   keywords: ['lab', 'laboratory', 'tests', 'results', 'specimens', 'pathology'],
  //   category: 'Clinical',
  // },
  // {
  //   id: 'pharmacy',
  //   label: 'Pharmacy',
  //   route: ROUTES.PHARMACY,
  //   description: 'Medication dispensing',
  //   moduleCode: 'pharmacy',
  //   keywords: ['pharmacy', 'medication', 'drugs', 'dispensing', 'prescriptions'],
  //   category: 'Clinical',
  // },

  // ══════════════════════════════════════════════════════════════════════════
  // FINANCE
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'billing',
    label: 'Billing Operations',
    route: ROUTES.BILLING,
    description: 'Billing intake, charge capture, receipts, invoices, and reconciliation',
    moduleCode: 'billing',
    keywords: ['billing', 'finance', 'payments', 'receipts', 'invoices', 'reconciliation'],
    category: 'Finance',
  },
  {
    id: 'billing-queue',
    label: 'Billing Queue',
    route: BILLING_ROUTES.PATIENT_QUEUE,
    description: 'Queue of visits ready for billing operations',
    moduleCode: 'billing',
    keywords: ['billing queue', 'queue', 'patient billing', 'charge capture'],
    category: 'Finance',
  },
  {
    id: 'billing-action-center',
    label: 'Billing Encounter',
    route: BILLING_ROUTES.BILLING_SPACE,
    description: 'Patient-context billing workspace for forward, status, and charge entry actions',
    moduleCode: 'billing',
    keywords: ['billing encounter', 'charge capture', 'billing tray', 'payment entry', 'visit status', 'forward patient'],
    category: 'Finance',
  },
  {
    id: 'billing-reconciliation',
    label: 'Receipts & Reconciliation',
    route: BILLING_ROUTES.RECEIPTS_RECONCILIATION,
    description: 'Review receipts and perform reconciliation',
    moduleCode: 'billing',
    keywords: ['receipts', 'reconciliation', 'billing review'],
    category: 'Finance',
  },
  {
    id: 'billing-invoices',
    label: 'Invoices',
    route: BILLING_ROUTES.INVOICES,
    description: 'Invoice records derived from receipts',
    moduleCode: 'billing',
    keywords: ['invoices', 'receipt-derived invoices', 'billing documents'],
    category: 'Finance',
  },
  {
    id: 'billing-intelligence',
    label: 'Financial Intelligence',
    route: BILLING_ROUTES.INTELLIGENCE,
    description: 'Financial analytics and revenue statistics',
    moduleCode: 'billing',
    keywords: ['financial intelligence', 'billing intelligence', 'billing stats', 'revenue analytics'],
    category: 'Finance',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ADMINISTRATION
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'administration',
    label: 'Facility Governance',
    route: ROUTES.ADMINISTRATION,
    description: 'Configure facilities, manage workforce access, services, and operational controls',
    moduleCode: 'administration',
    keywords: ['admin', 'administration', 'governance', 'facilities', 'management', 'settings'],
    category: 'Administration',
  },
  {
  id: 'admin-overview',
  label: 'Facility Intelligence',
  route: ADMIN_ROUTES.OVERVIEW,
  description: 'Administrative analytics dashboard for workforce, capacity, inventory, and revenue insights',
  moduleCode: 'administration',
  keywords: ['analytics', 'dashboard', 'intelligence', 'insights', 'metrics', 'workforce', 'capacity', 'inventory', 'revenue'],
  category: 'Administration',
},
  {
    id: 'admin-team',
    label: 'Workforce Administration',
    route: ADMIN_ROUTES.TEAM,
    description: 'Manage staff, invitations, roles, and team members',
    moduleCode: 'administration',
    keywords: ['team', 'staff', 'employees', 'workforce', 'invitations', 'roles', 'permissions'],
    category: 'Administration',
  },
  {
    id: 'admin-facility-setup',
    label: 'Clinical Departments',
    route: ADMIN_ROUTES.FACILITY_SETUP,
    description: 'Configure departments and facility structure',
    moduleCode: 'administration',
    keywords: ['facility', 'departments', 'structure', 'organization', 'clinical departments'],
    category: 'Administration',
  },
  {
    id: 'admin-service-catalog',
    label: 'Clinical & Billing Services',
    route: ADMIN_ROUTES.SERVICE_CATALOG,
    description: 'Manage services, procedures, and pricing versions',
    moduleCode: 'administration',
    keywords: ['services', 'catalog', 'pricing', 'procedures', 'billing services', 'clinical services'],
    category: 'Administration',
  },
  {
    id: 'admin-inventory',
    label: 'Supply & Inventory Management',
    route: ADMIN_ROUTES.INVENTORY,
    description: 'Manage stock items, locations, and inventory controls',
    moduleCode: 'administration',
    keywords: ['inventory', 'supplies', 'stock', 'items', 'locations', 'warehouse'],
    category: 'Administration',
  },
  {
    id: 'facility-admin-billing-review',
    label: 'Billing Cycle Review',
    route: ADMIN_ROUTES.BILLING_CYCLE_BILLING_REVIEW,
    description: 'Review and manage facility billing cycles, payment periods, and invoice schedules',
    moduleCode: 'administration',
    keywords: ['billing cycle', 'payment review', 'invoice review', 'billing period', 'payment schedule', 'cycle validation'],
    category: 'Administration',
  },
  {
    id: 'facility-admin-revenue-stats',
    label: 'Billing Cycle Revenue Statistics',
    route: ADMIN_ROUTES.BILLING_CYCLE_REVENUE_STATS,
    description: 'View revenue statistics, payment analytics, and financial performance across billing cycles',
    moduleCode: 'administration',
    keywords: ['revenue stats', 'billing analytics', 'payment statistics', 'financial performance', 'cycle revenue', 'billing insights'],
    category: 'Administration',
  },
  {
    id: 'clinical-rooms',
    label: 'Clinical Rooms',
    route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.CLINICAL_ROOMS,
    description: 'Manage clinical rooms and spaces',
    moduleCode: 'administration',
    keywords: ['rooms', 'clinical', 'space', 'facility', 'consultation'],
    category: 'Administration',
  },
  {
    id: 'ward-management',
    label: 'Ward Management',
    route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.WARD_MANAGEMENT,
    description: 'Manage hospital wards and bed allocation',
    moduleCode: 'administration',
    keywords: ['ward', 'beds', 'inpatient', 'unit', 'nursing unit'],
    category: 'Administration',
  },
  {
    id: 'facility-zones',
    label: 'Facility Zones',
    route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.FACILITY_ZONES,
    description: 'Define and manage facility zones',
    moduleCode: 'administration',
    keywords: ['zones', 'areas', 'sections', 'departments', 'facility layout'],
    category: 'Administration',
  },
  {
    id: 'space-allocation',
    label: 'Space Allocation',
    route: ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES.SPACE_ALLOCATION,
    description: 'Allocate staff to spaces and rooms',
    moduleCode: 'administration',
    keywords: ['allocation', 'assignment', 'staff', 'space', 'room assignment'],
    category: 'Administration',
  },
  {
    id: 'facility-identity',
    label: 'Facility Identity',
    route: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.FACILITY_IDENTITY,
    description: 'Manage facility profile and branding',
    moduleCode: 'administration',
    keywords: ['identity', 'profile', 'branding', 'facility info', 'details'],
    category: 'Administration',
  },
  {
    id: 'operational-policies',
    label: 'Operational Policies',
    route: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.OPERATIONAL_POLICIES,
    description: 'Configure facility operational policies',
    moduleCode: 'administration',
    keywords: ['policies', 'rules', 'guidelines', 'procedures', 'operations'],
    category: 'Administration',
  },
  // {
  //   id: 'available-plans',
  //   label: 'Available Plans',
  //   route: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.AVAILABLE_PLANS,
  //   description: 'Browse and manage available subscription plans',
  //   moduleCode: 'administration',
  //   keywords: ['plans', 'subscriptions', 'pricing', 'tiers', 'packages'],
  //   category: 'Administration',
  // },
  // {
  //   id: 'facility-subscriptions',
  //   label: 'Facility Subscriptions',
  //   route: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.SUBSCRIPTIONS,
  //   description: 'Manage facility subscriptions',
  //   moduleCode: 'administration',
  //   keywords: ['subscriptions', 'facility', 'plans', 'enrollment'],
  //   category: 'Administration',
  // },
  // {
  //   id: 'payments',
  //   label: 'Payments',
  //   route: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.PAYMENTS,
  //   description: 'Manage payment methods and history',
  //   moduleCode: 'administration',
  //   keywords: ['payments', 'billing', 'credit card', 'payment method'],
  //   category: 'Administration',
  // },

  // ══════════════════════════════════════════════════════════════════════════
  // PLATFORM ADMINISTRATION (super-admin only)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'platform-admin-facilities',
    label: 'Platform Administration - Facilities',
    route: PLATFORM_ADMIN_ROUTES.FACILITIES,
    description: 'Manage all facilities across the platform',
    moduleCode: 'platform_administration',
    keywords: ['platform', 'admin', 'facilities', 'global', 'system', 'management'],
    category: 'Platform Administration',
    requiredCapability: 'super_admin',
  },
  {
    id: 'platform-admin-users',
    label: 'Platform Administration - Users',
    route: PLATFORM_ADMIN_ROUTES.USERS,
    description: 'Manage all users across the platform',
    moduleCode: 'platform_administration',
    keywords: ['platform', 'admin', 'users', 'global', 'accounts', 'management'],
    category: 'Platform Administration',
    requiredCapability: 'super_admin',
  },
  {
    id: 'platform-admin-plans',
    label: 'Platform Plans & Subscriptions',
    route: PLATFORM_ADMIN_ROUTES.FACILITIES_PLANS,
    description: 'Manage global subscription plans and pricing',
    moduleCode: 'platform_administration',
    keywords: ['platform', 'plans', 'subscriptions', 'global', 'pricing'],
    category: 'Platform Administration',
    requiredCapability: 'super_admin',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ACCOUNT (always accessible)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'account-profile',
    label: 'My Profile',
    route: ACCOUNT_ROUTES.SETTINGS_PROFILE,
    description: 'Maintain and update your account identity information',
    moduleCode: 'account',
    keywords: ['profile', 'personal', 'information', 'details', 'name', 'contact'],
    category: 'Account',
  },
  {
    id: 'account-security',
    label: 'Account Security',
    route: ACCOUNT_ROUTES.SETTINGS_SECURITY,
    description: 'Configure password policies and multi-factor authentication',
    moduleCode: 'account',
    keywords: ['security', 'password', 'mfa', 'authentication', 'login', '2fa'],
    category: 'Account',
  },
  {
    id: 'account-preferences',
    label: 'User Preferences',
    route: ACCOUNT_ROUTES.SETTINGS_PREFERENCES,
    description: 'Customize interface behaviour and system experience',
    moduleCode: 'account',
    keywords: ['preferences', 'settings', 'theme', 'language', 'notifications'],
    category: 'Account',
  },
  {
    id: 'account-invitations',
    label: 'Invitations',
    route: ACCOUNT_ROUTES.INVITATIONS,
    description: 'Manage facility and team invitations',
    moduleCode: 'account',
    keywords: ['invitations', 'facility', 'team', 'join', 'access', 'invites'],
    category: 'Account',
  },
  {
    id: 'message-center',
    label: 'Message Center',
    route: ACCOUNT_ROUTES.MESSAGES,
    description: 'Inbox and message center',
    moduleCode: 'account',
    keywords: ['messages', 'inbox', 'communication', 'notifications', 'chat'],
    category: 'Account',
  },
  {
    id: 'compose-message',
    label: 'Compose Message',
    route: ACCOUNT_ROUTES.MESSAGES_COMPOSE,
    description: 'Write and send new messages',
    moduleCode: 'account',
    keywords: ['compose', 'write', 'send', 'new message', 'email'],
    category: 'Account',
  },
  {
    id: 'message-inbox',
    label: 'Message Inbox',
    route: ACCOUNT_ROUTES.MESSAGES_INBOX,
    description: 'View received messages',
    moduleCode: 'account',
    keywords: ['inbox', 'received', 'messages', 'unread'],
    category: 'Account',
  },
  {
    id: 'sent-messages',
    label: 'Sent Messages',
    route: ACCOUNT_ROUTES.MESSAGES_SENT,
    description: 'View sent messages',
    moduleCode: 'account',
    keywords: ['sent', 'outbox', 'sent items'],
    category: 'Account',
  },
  {
    id: 'draft-messages',
    label: 'Draft Messages',
    route: ACCOUNT_ROUTES.MESSAGES_DRAFT,
    description: 'View and edit draft messages',
    moduleCode: 'account',
    keywords: ['draft', 'unsent', 'saved'],
    category: 'Account',
  },
  {
    id: 'trash-messages',
    label: 'Trash',
    route: ACCOUNT_ROUTES.MESSAGES_TRASH,
    description: 'View deleted messages',
    moduleCode: 'account',
    keywords: ['trash', 'deleted', 'bin', 'recycle'],
    category: 'Account',
  },
];
