/**
 * ============================================================================
 * STREAMLINED PATIENT ONBOARDING - MINIMAL DATA COLLECTION
 * ============================================================================
 * 
 * DESIGN PHILOSOPHY: Minimal data at first contact. Clinical relevance only.
 * 
 * DATA COLLECTION (STRICT):
 * - date_of_birth (date)
 * - biological_sex (male/female/intersex/unknown)
 * - emergency_contact (nested JSON object)
 * 
 * BACKEND INTEGRATION:
 * - Patient ID generated by backend after submission
 * - Clean payload structure matching API expectations
 * - Proper loading, success, and error state handling
 * - Toast notifications for user feedback
 */

import React, { useState, useCallback, useMemo, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useReactToPrint } from 'react-to-print';
import { 
  User, 
  Phone, 
  Calendar,
  Shield,
  Check,
  ArrowRight,
  Sun,
  Moon,
  Users,
  ChevronLeft,
  BadgeCheck,
  AlertCircle,
  Loader2,
  Printer,
} from 'lucide-react';
import { cn } from '../../../../../shared/types/cn';
import { useAppDispatch, useAppSelector } from '../../../../../app/store/hooks/useApp';
import { toggleTheme } from '../../../../../app/store/slices/uiSlice';
import { ROUTES } from '../../routes/onboardingRouteConstants';
import { useRegisterPatient } from '../../api/queries/register-patient/queries/registerpatientQuery';
import type { RegisterPatientRequest } from '../../api/queries/register-patient/queries/registerPatientTypes';
import LogoImage from '../../../../../shared/assets/LogoImage';
import { BrandName } from '../../../../../shared/utils/BrandName';
import { PatientRegistrationPrintout } from '../../../../../shared/components/Printout/PatientRegistrationPrintout';
import { formatPrintTime } from '../../../../../shared/components/Printout/printoutUtils';
import { countryCodes, type CountryCode } from '../auth/countryCodes';

/* ==========================================================================
   TYPE DEFINITIONS
   ========================================================================== */

/**
 * Biological sex options (as per backend specification)
 */
type BiologicalSex = 'male' | 'female' | 'intersex' | 'unknown';

/**
 * Emergency contact structure
 */
interface EmergencyContact {
  full_name: string;
  phone: string;
  phoneCountryCode: string;
  relationship: string;
}

/**
 * Form data structure (client-side state)
 */
interface PatientFormData {
  date_of_birth: string;
  biological_sex: BiologicalSex | '';
  emergency_contact: EmergencyContact;
}

/* ==========================================================================
   DATA CONSTANTS
   ========================================================================== */

const BIOLOGICAL_SEX_OPTIONS: Array<{ value: BiologicalSex; label: string }> = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'intersex', label: 'Intersex' },
  { value: 'unknown', label: 'Prefer not to disclose' }
];

const RELATIONSHIP_OPTIONS = [
  'Spouse/Partner',
  'Parent',
  'Child',
  'Sibling',
  'Friend',
  'Other Family Member',
  'Guardian',
  'Other'
];

/* ==========================================================================
   MAIN COMPONENT
   ========================================================================== */

export const PatientOnboarding: React.FC = () => {
   const dispatch = useAppDispatch();
   const navigate = useNavigate();
   const theme = useAppSelector((state) => state.ui.theme);
   
   // Icon styling (reused across form fields)
   const iconClass = cn(
     'absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4',
     theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
   );
   
    // Form state
   const [currentStage, setCurrentStage] = useState<1 | 2>(1);
   const [formData, setFormData] = useState<PatientFormData>({
     date_of_birth: '',
     biological_sex: '',
     emergency_contact: {
       full_name: '',
       phone: '',
       phoneCountryCode: '+256',
       relationship: '',
     },
   });
   
   // Touched state for validation feedback
   const [touched, setTouched] = useState<Record<string, boolean>>({});
   
   // Country selector state
   const [isCountryDropdownOpen, setIsCountryDropdownOpen] = useState(false);
   const [filterCountry, setFilterCountry] = useState('');
   
   // Selected country memo
    const selectedCountry = useMemo(
      () => countryCodes.find((c: CountryCode) => c.dial_code === formData.emergency_contact.phoneCountryCode) || countryCodes.find((c: CountryCode) => c.dial_code === '+256') || countryCodes[0],
      [formData.emergency_contact.phoneCountryCode]
    );
   
   // Filtered countries
   const filteredCountries = useMemo(() => {
     if (!filterCountry) return countryCodes;
     const search = filterCountry.toLowerCase();
      return countryCodes.filter(
        (country: CountryCode) =>
          country.name.toLowerCase().includes(search) ||
         country.code.includes(search) ||
         country.dial_code.includes(search)
     );
   }, [filterCountry]);
   
   // Handlers
   const handleCountrySelect = (dial_code: string) => {
     updateEmergencyContact('phoneCountryCode', dial_code);
     setIsCountryDropdownOpen(false);
     setFilterCountry('');
     // Reset touched state for phoneCountryCode when it changes (if it was previously touched)
     if (touched['phoneCountryCode']) {
       setTouched(prev => ({ ...prev, ['phoneCountryCode']: false }));
     }
   };
   
   const handleBlur = (field: keyof EmergencyContact) => () => {
     setTouched(prev => ({ ...prev, [field]: true }));
   };
   
  
  
  // Backend mutation hook
  const registerPatientMutation = useRegisterPatient({
    autoNavigateToDashboard: false,
    autoSwitchToPatientMode: true,
    onSuccess: (data) => {
      // Success is handled by the mutation hook (toast notification)
      // Store patient UUID for dashboard navigation
      console.log('Patient registered successfully:', data.data.patient_uuid);
    },
    onError: (error) => {
      // Error is handled by the mutation hook (toast notification)
      console.error('Patient registration failed:', error);
    }
  });

  /* ==========================================================================
     FORM HANDLERS
     ========================================================================== */

  /**
   * Update basic form fields
   */
  const updateField = useCallback((field: 'date_of_birth' | 'biological_sex', value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  }, []);

  /**
   * Update emergency contact nested fields
   */
  const updateEmergencyContact = useCallback(
    (field: keyof EmergencyContact, value: string) => {
      setFormData(prev => ({
        ...prev,
        emergency_contact: {
          ...prev.emergency_contact,
          [field]: value
        }
      }));
    },
    []
  );

  /* ==========================================================================
     FORM VALIDATION
     ========================================================================== */

  /**
   * Validate Stage 1: Basic Information
   */
  const isStage1Valid = useMemo(() => {
    return formData.date_of_birth !== '' && formData.biological_sex !== '';
  }, [formData.date_of_birth, formData.biological_sex]);

/**
    * Validate Stage 2: Emergency Contact
    */
  const isStage2Valid = useMemo(() => {
    const { full_name, phone, phoneCountryCode, relationship } = formData.emergency_contact;
    if (full_name.trim() === '' || phone.trim() === '' || phoneCountryCode.trim() === '' || relationship.trim() === '') {
      return false;
    }
    
    // Validate phone number (digits only, reasonable length)
    const digitsOnly = phone.replace(/\D/g, '');
    if (digitsOnly.length < 6 || digitsOnly.length > 15) {
      return false;
    }
    
    return true;
  }, [formData.emergency_contact]);

  /**
   * Overall form validation
   */
  const isFormComplete = useMemo(() => {
    return isStage1Valid && isStage2Valid;
  }, [isStage1Valid, isStage2Valid]);

  /* ==========================================================================
     FORM SUBMISSION
     ========================================================================== */

  /**
   * Prepare clean payload for backend submission
   */
  const { user } = useAppSelector((state) => state.auth);

const prepareSubmissionPayload = useCallback((): RegisterPatientRequest => {
    if (!user?.id) {
      throw new Error('User ID is required to register a patient');
    }
    
    // Clean phone number (digits only) and combine with country code
    const cleanPhone = formData.emergency_contact.phone.replace(/\D/g, '');
    const fullPhone = formData.emergency_contact.phoneCountryCode + cleanPhone;
    
    return {
      date_of_birth: formData.date_of_birth,
      biological_sex: formData.biological_sex as BiologicalSex,
      emergency_contact_chain_encrypted: {
        full_name: formData.emergency_contact.full_name.trim(),
        phone: fullPhone,
        relationship: formData.emergency_contact.relationship.trim(),
      },
      // Add the user ID
      user_id: user.id,
    };
  }, [formData, user]); // Add user to dependencies

  /**
   * Submit form to backend using React Query mutation
   */
  const handleSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate form completeness
    if (!isFormComplete) {
      return;
    }

    // Prepare and submit payload
    const payload = prepareSubmissionPayload();
    registerPatientMutation.mutate(payload);
  }, [isFormComplete, prepareSubmissionPayload, registerPatientMutation]);

  /**
   * Navigate to dashboard after successful registration
   */
  const handleContinueToDashboard = useCallback(() => {
    if (!registerPatientMutation.data?.data) {
      return;
    }

    const patientData = registerPatientMutation.data.data;
    
    navigate(ROUTES.PATIENT_DASHBOARD, {
      state: {
        patientID: patientData.patient_uuid,
        patientUUID: patientData.patient_uuid,
        isNewPatient: true,
        dateOfBirth: patientData.date_of_birth,
        biologicalSex: patientData.biological_sex,
      }
    });
  }, [registerPatientMutation.data, navigate]);

  /* ==========================================================================
     COMPUTED STATE
     ========================================================================== */

  const isSubmitting = registerPatientMutation.isPending;
  const isComplete = registerPatientMutation.isSuccess;
  const registeredPatientID = registerPatientMutation.data?.data?.patient_uuid || '';
  const printoutRef = useRef<HTMLDivElement>(null);
  const patientName = user?.name || user?.profile?.full_name || 'Patient';
  const [printTimestamp, setPrintTimestamp] = useState('');

  const handlePrint = useReactToPrint({
    contentRef: printoutRef,
    documentTitle: `Patient_${registeredPatientID}`,
    onBeforePrint: async () => {
      setPrintTimestamp(formatPrintTime());
    },
  });

  /* ==========================================================================
     RENDER COMPONENTS
     ========================================================================== */

  /**
   * Progress Indicator
   */
  const renderProgress = () => {
    const progress = currentStage === 1 ? 50 : 100;
    
    return (
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className={cn(
              "text-2xl font-bold",
              theme === 'dark' ? "text-white" : "text-slate-900"
            )}>
              {currentStage === 1 ? "Basic Information" : "Emergency Contact"}
            </h2>
            <p className={cn(
              "text-sm mt-1",
              theme === 'dark' ? "text-slate-400" : "text-slate-600"
            )}>
              Step {currentStage} of 2
            </p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-blue-600">
              {progress}%
            </div>
          </div>
        </div>

        <div className="relative h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden">
          <motion.div
            className="absolute top-0 left-0 h-full rounded-full bg-gradient-to-r from-blue-600 to-emerald-600"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.5, ease: "easeOut" }}
          />
        </div>
      </div>
    );
  };

  /**
   * Reusable Input Field Component
   */
  const renderInput = (
    value: string,
    onChange: (value: string) => void,
    label: string,
    type: 'text' | 'date' | 'tel' | 'select' = 'text',
    icon?: React.ReactNode,
    placeholder?: string,
    options?: Array<{ value: string; label: string }> | string[]
  ) => {
    const isEmpty = !value;
    
    return (
      <div className="space-y-2">
        <label className={cn(
          "block text-sm font-medium",
          theme === 'dark' ? "text-white" : "text-slate-900"
        )}>
          {label}
        </label>
        
        <div className="relative">
          {icon && (
            <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 z-10">
              {icon}
            </div>
          )}
          
          {type === 'select' && options ? (
            <select
              value={value}
              onChange={(e) => onChange(e.target.value)}
              className={cn(
                "w-full px-4 py-3 rounded-xl border-2 appearance-none",
                "focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all",
                theme === 'dark'
                  ? "bg-slate-800 border-slate-700 text-white"
                  : "bg-white border-slate-200 text-slate-900",
                icon ? "pl-11" : undefined,
                !isEmpty && "border-emerald-500"
              )}
            >
              <option value="">Select {label.toLowerCase()}</option>
              {options.map((opt) => {
                const optValue = typeof opt === 'string' ? opt : opt.value;
                const optLabel = typeof opt === 'string' ? opt : opt.label;
                return (
                  <option key={optValue} value={optValue}>
                    {optLabel}
                  </option>
                );
              })}
            </select>
          ) : (
            <input
              type={type}
              value={value}
              onChange={(e) => onChange(e.target.value)}
              placeholder={placeholder}
              max={type === 'date' ? new Date().toISOString().split('T')[0] : undefined}
              className={cn(
                "w-full px-4 py-3 rounded-xl border-2",
                "focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all",
                theme === 'dark'
                  ? "bg-slate-800 border-slate-700 text-white placeholder-slate-500"
                  : "bg-white border-slate-200 text-slate-900 placeholder-slate-400",
                icon ? "pl-11" : undefined,
                !isEmpty && "border-emerald-500"
              )}
            />
          )}
          
          {!isEmpty && (
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              className="absolute right-3 top-1/2 -translate-y-1/2 z-10"
            >
              <Check className="w-5 h-5 text-emerald-500" />
            </motion.div>
          )}
        </div>
      </div>
    );
  };

  /**
   * Form Sections
   */
  const renderFormSection = () => (
    <form onSubmit={handleSubmit} className="space-y-6">
      <AnimatePresence mode="wait">
        {/* Stage 1: Basic Information */}
        {currentStage === 1 && (
          <motion.div 
            key="stage-1"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="space-y-6"
          >
            {renderInput(
              formData.date_of_birth,
              (value) => updateField('date_of_birth', value),
              'Date of Birth',
              'date',
              <Calendar className="w-5 h-5" />
            )}
            
            {renderInput(
              formData.biological_sex,
              (value) => updateField('biological_sex', value),
              'Biological Sex',
              'select',
              <Users className="w-5 h-5" />,
              undefined,
              BIOLOGICAL_SEX_OPTIONS
            )}

            <div className={cn(
              "p-4 rounded-xl border-2 flex items-start gap-3",
              theme === 'dark' 
                ? "bg-blue-900/20 border-blue-800" 
                : "bg-blue-50 border-blue-200"
            )}>
              <Shield className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className={cn(
                  "font-semibold mb-1",
                  theme === 'dark' ? "text-blue-300" : "text-blue-900"
                )}>
                  Privacy & Security
                </p>
                <p className={cn(
                  "text-xs",
                  theme === 'dark' ? "text-blue-400" : "text-blue-700"
                )}>
                  Your information is encrypted and HIPAA-compliant. We collect minimal data for clinical relevance only.
                </p>
              </div>
            </div>
          </motion.div>
        )}

        {/* Stage 2: Emergency Contact */}
        {currentStage === 2 && (
          <motion.div 
            key="stage-2"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="space-y-6"
          >
            <div className={cn(
              "p-4 rounded-xl border-2",
              theme === 'dark' 
                ? "bg-slate-800/50 border-slate-700" 
                : "bg-slate-50 border-slate-200"
            )}>
              <h3 className={cn(
                "text-lg font-semibold mb-1 flex items-center gap-2",
                theme === 'dark' ? "text-white" : "text-slate-900"
              )}>
                <AlertCircle className="w-5 h-5 text-red-500" />
                Emergency Contact Information
              </h3>
              <p className={cn(
                "text-xs",
                theme === 'dark' ? "text-slate-400" : "text-slate-600"
              )}>
                This person will be contacted in case of a medical emergency
              </p>
            </div>

            {renderInput(
              formData.emergency_contact.full_name,
              (value) => updateEmergencyContact('full_name', value),
              'Full Name',
              'text',
              <User className="w-5 h-5" />,
              'John Doe'
            )}

<div className="space-y-2">
            <label className={cn(
              "block text-sm font-medium",
              theme === 'dark' ? "text-white" : "text-slate-900"
            )}>
              Phone Number
            </label>
            
            <div className="relative">
              <div className="flex gap-2">
                {/* Country Code Selector */}
                <div className="relative flex-shrink-0 w-36">
                  <button
                    type="button"
                    onClick={() => setIsCountryDropdownOpen(!isCountryDropdownOpen)}
                    className={cn(
                      'w-full py-2.5 px-3 rounded-lg border-2 text-sm text-left',
                      'focus:outline-none focus:ring-2 transition-all duration-150',
                      'flex items-center justify-between gap-2',
                      theme === 'dark'
                        ? 'bg-gray-900/60 text-white border-gray-700 hover:border-cyan-500 focus:ring-cyan-500/30'
                        : 'bg-white text-gray-900 border-gray-300 hover:border-blue-500 focus:ring-blue-200'
                    )}
                    disabled={isSubmitting}
                  >
                    <span className="flex items-center gap-1.5 truncate">
                      <span className="text-base">{selectedCountry.flag}</span>
                      <span className="font-medium">{selectedCountry.dial_code}</span>
                    </span>
                    <svg
                      className="w-4 h-4 flex-shrink-0"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </button>

                  {/* Dropdown */}
                  {isCountryDropdownOpen && (
                    <div
                      className={cn(
                        'absolute z-50 w-72 mt-1 rounded-lg border-2 shadow-xl',
                        'max-h-64 overflow-hidden flex flex-col',
                        theme === 'dark' ? 'bg-gray-900 border-gray-700' : 'bg-white border-gray-300'
                      )}
                    >
                      <div
                        className="p-2 border-b"
                        style={{ borderColor: theme === 'dark' ? '#374151' : '#e5e7eb' }}
                      >
                        <input
                          type="text"
                          value={filterCountry}
                          onChange={(e) => setFilterCountry(e.target.value)}
                          placeholder="Search country..."
                          className={cn(
                            'w-full px-3 py-1.5 text-xs rounded border',
                            'focus:outline-none focus:ring-1',
                            theme === 'dark'
                              ? 'bg-gray-800 border-gray-700 text-white placeholder-gray-500 focus:ring-cyan-500'
                              : 'bg-gray-50 border-gray-300 text-gray-900 placeholder-gray-400 focus:ring-blue-500'
                          )}
                          autoFocus
                        />
                      </div>

                      <div className="overflow-y-auto">
                        {filteredCountries.length > 0 ? (
                          filteredCountries.map((country: CountryCode) => (
                            <button
                              key={country.code}
                              type="button"
                              onClick={() => handleCountrySelect(country.dial_code)}
                              className={cn(
                                'w-full px-3 py-2 text-left text-sm',
                                'hover:bg-opacity-50 transition-colors',
                                'flex items-center gap-2',
                                theme === 'dark'
                                  ? 'hover:bg-gray-800 text-white'
                                  : 'hover:bg-gray-100 text-gray-900',
                                country.dial_code === formData.emergency_contact.phoneCountryCode &&
                                  (theme === 'dark' ? 'bg-gray-800' : 'bg-blue-50')
                              )}
                            >
                              <span className="text-lg">{country.flag}</span>
                              <span className="flex-1 truncate">{country.name}</span>
                              <span
                                className={cn(
                                  'font-medium text-xs',
                                  theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
                                )}
                              >
                                {country.dial_code}
                              </span>
                            </button>
                          ))
                        ) : (
                          <div
                            className={cn(
                              'px-3 py-4 text-center text-sm',
                              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                            )}
                          >
                            No countries found
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>

                {/* Phone Input */}
                <div className="relative flex-1">
                  <Phone className={iconClass} />
                  <input
                    type="tel"
                    value={formData.emergency_contact.phone}
                    onChange={(e) => {
                      const value = e.target.value.replace(/[^\d\s\-()]/g, '');
                      updateEmergencyContact('phone', value);
                    }}
                    onBlur={handleBlur('phone')}
                    placeholder="e.g., 712 345 678"
                    className={cn(
                      "w-full px-4 py-3 rounded-xl border-2 pl-11",
                      "focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all",
                      theme === 'dark'
                        ? "bg-slate-800 border-slate-700 text-white placeholder-slate-500"
                        : "bg-white border-slate-200 text-slate-900 placeholder-slate-400",
                      formData.emergency_contact.phone && "border-emerald-500"
                    )}
                    disabled={isSubmitting}
                  />
                  {formData.emergency_contact.phone && (
                    <Check className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-emerald-500" />
                  )}
                </div>
              </div>
            </div>
            
            {/* Display formatted number */}
            {formData.emergency_contact.phone && (
              <p className={cn('text-xs mt-1', theme === 'dark' ? 'text-gray-400' : 'text-gray-600')}>
                {formData.emergency_contact.phone.length < 3 ? 'Typing..: ' : 'Number: '}
                <span className="font-mono text-blue-600">
                  {formData.emergency_contact.phoneCountryCode} {formData.emergency_contact.phone}
                </span>
              </p>
            )}
            
            {/* Error message */}
            {touched['phone'] && formData.emergency_contact.phone && formData.emergency_contact.phone.replace(/\D/g, '').length < 6 && (
              <p className="text-xs text-red-500 mt-1 flex items-center gap-1">
                <AlertCircle className="w-3 h-3" />
                Phone number too short
              </p>
            )}
          </div>

            {renderInput(
              formData.emergency_contact.relationship,
              (value) => updateEmergencyContact('relationship', value),
              'Relationship',
              'select',
              <Users className="w-5 h-5" />,
              undefined,
              RELATIONSHIP_OPTIONS
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Navigation */}
      <div className="flex justify-between pt-6">
        {/* Back button - Always visible on all steps */}
        <button
          type="button"
          onClick={() => {
            if (currentStage === 1) {
              // On first step, go back to previous page
              navigate(-1);
            } else {
              // On second step, go back to step 1
              setCurrentStage(1);
            }
          }}
          disabled={isSubmitting}
          className={cn(
            "flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-all border-2",
            // Cursor classes
            !isSubmitting ? "cursor-pointer" : "cursor-not-allowed",
            // Theme-based styling
            theme === 'dark'
              ? "border-slate-700 text-slate-300 hover:bg-slate-800"
              : "border-slate-300 text-slate-700 hover:bg-slate-50",
            isSubmitting && "opacity-50"
          )}
        >
          <ChevronLeft className="w-5 h-5" />
          {currentStage === 1 ? 'Back' : 'Back'}
        </button>
        
        {/* Right side buttons - Continue or Submit */}
        {currentStage < 2 ? (
          <button
            type="button"
            disabled={!isStage1Valid || isSubmitting}
            onClick={() => setCurrentStage(2)}
            className={cn(
              "ml-auto flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all",
              // Cursor classes
              isStage1Valid && !isSubmitting ? "cursor-pointer" : "cursor-not-allowed",
              // Style based on validity
              isStage1Valid && !isSubmitting
                ? "bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700"
                : "bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400",
              isSubmitting && "opacity-50"
            )}
          >
            Continue
            <ArrowRight className="w-5 h-5" />
          </button>
        ) : (
          <button
            type="submit"
            disabled={!isFormComplete || isSubmitting}
            className={cn(
              "ml-auto flex items-center gap-2 px-8 py-3 rounded-xl font-bold transition-all",
              // Cursor classes
              isFormComplete && !isSubmitting ? "cursor-pointer" : "cursor-not-allowed",
              // Style based on validity
              isFormComplete && !isSubmitting
                ? "bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700"
                : "bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400",
              isSubmitting && "opacity-50"
            )}
          >
            {isSubmitting ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Submitting...
              </>
            ) : (
              <>
                <BadgeCheck className="w-5 h-5" />
                Complete Registration
              </>
            )}
          </button>
        )}
      </div>
    </form>
  );

  /**
   * Success Screen - Display Backend-Generated Patient ID
   */
  const renderSuccessScreen = () => (
    <div className="space-y-8 text-center">
      <motion.div
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: "spring", duration: 0.6 }}
      >
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 mb-6 shadow-xl">
          <BadgeCheck className="w-10 h-10 text-white" />
        </div>
      </motion.div>

          <div>
            <h2 className={cn(
              "text-3xl font-bold mb-3",
              theme === 'dark' ? "text-white" : "text-slate-900"
            )}>
              Registration Complete!
            </h2>
            <p className={cn(
              "text-lg",
              theme === 'dark' ? "text-slate-400" : "text-slate-600"
            )}>
              Your patient account has been created successfully
            </p>
          </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className={cn(
          "rounded-2xl border-2 p-8",
          theme === 'dark'
            ? "bg-slate-800 border-slate-700"
            : "bg-white border-slate-200"
        )}
      >
       <div className="mb-6">
  <p
    className={cn(
      "text-sm font-medium mb-2",
      theme === 'dark' ? "text-slate-400" : "text-slate-600"
    )}
  >
    Your Patient Number
  </p>

  <div className="text-3xl md:text-4xl font-black tracking-tight bg-gradient-to-r from-blue-600 to-emerald-600 bg-clip-text text-transparent break-all">
    {registeredPatientID}
  </div>

  <p
    className={cn(
      "text-xs mt-2",
      theme === 'dark' ? "text-slate-500" : "text-slate-500"
    )}
  >
    Please keep this Number for your records. You may be asked for it when visiting any health facility using Custocare.
  </p>
</div>


        <div className={cn(
          "p-4 rounded-xl border mb-6",
          theme === 'dark'
            ? "bg-slate-900/50 border-slate-700"
            : "bg-slate-50 border-slate-200"
        )}>
          <div className="flex items-center justify-center gap-2 mb-2">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="font-semibold text-emerald-600">Account Active</span>
          </div>
          <p className={cn(
            "text-xs",
            theme === 'dark' ? "text-slate-400" : "text-slate-600"
          )}>
            You can now access the patient portal
          </p>
        </div>

        <button
          onClick={handleContinueToDashboard}
          className="w-full flex items-center justify-center gap-3 px-8 py-4 rounded-xl font-bold text-lg bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:from-blue-700 hover:to-emerald-700 transition-all"
        >
          Continue to Patient Portal
          <ArrowRight className="w-6 h-6" />
        </button>

        <button
          onClick={() => handlePrint()}
          className={cn(
            "w-full flex items-center justify-center gap-3 px-8 py-4 rounded-xl font-bold text-lg border-2 transition-all cursor-pointer mt-3",
            theme === 'dark'
              ? "border-slate-600 text-slate-300 hover:bg-slate-700"
              : "border-slate-300 text-slate-700 hover:bg-slate-100"
          )}
        >
          <Printer className="w-5 h-5" />
          Print / Download
        </button>
      </motion.div>

      <div className="hidden">
        <PatientRegistrationPrintout
          ref={printoutRef}
          patientName={patientName}
          patientNumber={registeredPatientID}
          facility={null}
          printTimestamp={printTimestamp}
        />
      </div>
    </div>
  );

  /* ==========================================================================
     MAIN RENDER
     ========================================================================== */

  return (
    <div className={cn(
      "min-h-screen flex flex-col relative",
      theme === 'dark' 
        ? "bg-gradient-to-br from-slate-950 via-gray-900 to-slate-950" 
        : "bg-gradient-to-br from-slate-50 via-white to-blue-50/40"
    )}>
      {/* Decorative Background */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className={cn(
          "absolute -top-32 -right-32 w-[600px] h-[600px] rounded-full blur-3xl",
          theme === 'dark' ? "bg-blue-600/20" : "bg-blue-400/15"
        )} />
        <div className={cn(
          "absolute -bottom-32 -left-32 w-[600px] h-[600px] rounded-full blur-3xl",
          theme === 'dark' ? "bg-emerald-600/20" : "bg-emerald-400/15"
        )} />
      </div>

      {/* Header */}
      <header className={cn(
        "sticky top-0 z-50 border-b backdrop-blur-xl",
        theme === 'dark' 
          ? "bg-slate-900/75 border-slate-800/60" 
          : "bg-white/75 border-slate-200/60"
      )}>
        <nav className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <LogoImage></LogoImage>
              <div>
                <div className="text-xl font-bold tracking-tight bg-linear-to-r from-blue-600 to-emerald-600 bg-clip-text text-transparent">
                  <BrandName></BrandName>
                </div>
                <div className={cn(
                  "text-[11px] font-semibold tracking-wide uppercase",
                  theme === 'dark' ? "text-slate-500" : "text-slate-500"
                )}>
                Set Up Your Health Profile
                </div>
              </div>
            </div>

            <button
              onClick={() => dispatch(toggleTheme())}
              className={cn(
                "p-3 rounded-xl transition-all border-2",
                theme === 'dark'
                  ? 'bg-slate-800/60 border-slate-700/60 text-amber-300'
                  : 'bg-slate-100 border-slate-200 text-slate-600'
              )}
            >
              {theme === 'dark' ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          </div>
        </nav>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex items-center justify-center px-4 py-12 relative z-10">
        <div className="w-full max-w-2xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={cn(
              "rounded-3xl border-2 p-8 backdrop-blur-xl shadow-2xl",
              theme === 'dark'
                ? "bg-slate-800/85 border-slate-700/60"
                : "bg-white/90 border-slate-200/60"
            )}
          >
            {!isComplete ? (
              <>
                {renderProgress()}
                {renderFormSection()}
              </>
            ) : (
              renderSuccessScreen()
            )}
          </motion.div>
        </div>
      </main>

      {/* Footer */}
      <footer className={cn(
        "py-6 px-4 border-t backdrop-blur-xl",
        theme === 'dark' 
          ? "bg-slate-900/60 border-slate-800/60" 
          : "bg-white/60 border-slate-200/60"
      )}>
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Shield className="w-4 h-4 text-emerald-500" />
            <span className={cn(
              "text-sm font-semibold",
              theme === 'dark' ? "text-slate-300" : "text-slate-700"
            )}>
              HIPAA Compliant • 256-bit Encryption
            </span>
          </div>
          <p className={cn(
            "text-xs",
            theme === 'dark' ? "text-slate-500" : "text-slate-500"
          )}>
            © {new Date().getFullYear()} Custocare. All information is encrypted and protected.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default PatientOnboarding;