import { ROUTES } from './shared.paths';

export const ADMINISTRATION_CLINICAL_SPACE_MGT_ROUTES = {
  ROOT: `${ROUTES.ADMINISTRATION}/clinical-space-management`,

  OVERVIEW: `${ROUTES.ADMINISTRATION}/clinical-space-management/overview`,

  CLINICAL_ROOMS: `${ROUTES.ADMINISTRATION}/clinical-space-management/clinical-rooms`,
  CLINICAL_ROOMS_CREATE: `${ROUTES.ADMINISTRATION}/clinical-space-management/clinical-rooms/create`,
  CLINICAL_ROOMS_SEARCH: `${ROUTES.ADMINISTRATION}/clinical-space-management/clinical-rooms/search`,

  WARD_MANAGEMENT: `${ROUTES.ADMINISTRATION}/clinical-space-management/wards`,
  WARD_CREATE: `${ROUTES.ADMINISTRATION}/clinical-space-management/wards/create`,
  WARD_OCCUPANCY: `${ROUTES.ADMINISTRATION}/clinical-space-management/wards/occupancy`,

  FACILITY_ZONES: `${ROUTES.ADMINISTRATION}/clinical-space-management/facility-zones`,
  FACILITY_ZONES_CREATE: `${ROUTES.ADMINISTRATION}/clinical-space-management/facility-zones/create`,

  SPACE_ALLOCATION: `${ROUTES.ADMINISTRATION}/clinical-space-management/space-allocation`,
  SPACE_ALLOCATION_ASSIGN: `${ROUTES.ADMINISTRATION}/clinical-space-management/space-allocation/assign`,
  SPACE_ALLOCATION_HISTORY: `${ROUTES.ADMINISTRATION}/clinical-space-management/space-allocation/history`,
} as const;

/** Relative segments for nested `<Route>` definitions under `/administration/settings`. */
export const ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS = {
  ROOT: 'settings',
  FACILITY_IDENTITY: 'identity',
  OPERATIONAL_POLICIES: 'policies',
} as const;

export const ADMINISTRATION_FACILITY_SETTINGS_ROUTES = {
  ROOT: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS.ROOT}`,
  FACILITY_IDENTITY: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS.FACILITY_IDENTITY}`,
  OPERATIONAL_POLICIES: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_FACILITY_SETTINGS_ROUTE_SEGMENTS.OPERATIONAL_POLICIES}`,
} as const;

/** Relative segments for nested `<Route>` definitions under `/administration/plans-subscriptions`. */
export const ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS = {
  ROOT: 'plans-subscriptions',
  AVAILABLE_PLANS: 'plans',
  SUBSCRIPTIONS: 'subscriptions',
  PAYMENTS: 'payment-methods',
  INVOICES: 'invoices',
  BILLING_DETAILS: 'billing-details',
} as const;

export const ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES = {
  ROOT: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}`,
  AVAILABLE_PLANS: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.AVAILABLE_PLANS}`,
  SUBSCRIPTIONS: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.SUBSCRIPTIONS}`,
  PAYMENTS: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.PAYMENTS}`,
  INVOICES: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.INVOICES}`,
  BILLING_DETAILS: `${ROUTES.ADMINISTRATION}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.ROOT}/${ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTE_SEGMENTS.BILLING_DETAILS}`,
} as const;

export const ADMIN_ROUTES = {
  ROOT: ROUTES.ADMINISTRATION,

  OVERVIEW: `${ROUTES.ADMINISTRATION}/overview`,

  TEAM: `${ROUTES.ADMINISTRATION}/team`,

  FACILITY_SETUP: `${ROUTES.ADMINISTRATION}/facility-setup`,

  SERVICE_CATALOG: `${ROUTES.ADMINISTRATION}/service-catalog`,

  INVENTORY: `${ROUTES.ADMINISTRATION}/inventory`,

  BILLING_CYCLE: `${ROUTES.ADMINISTRATION}/billing-cycle-management`,
  BILLING_CYCLE_REVENUE_STATS: `${ROUTES.ADMINISTRATION}/billing-cycle-management/billing-stats`,
  BILLING_CYCLE_BILLING_REVIEW: `${ROUTES.ADMINISTRATION}/billing-cycle-management/billing-review`,

  SPACE_GOVERNANCE: `${ROUTES.ADMINISTRATION}/space-governance`,
  CLINICAL_ROOMS: `${ROUTES.ADMINISTRATION}/space-governance/clinical-rooms`,
  WARD_MANAGEMENT: `${ROUTES.ADMINISTRATION}/space-governance/ward-management`,
  FACILITY_ZONES: `${ROUTES.ADMINISTRATION}/space-governance/facility-zones`,
  SPACE_ALLOCATION: `${ROUTES.ADMINISTRATION}/space-governance/space-allocation`,

  PLANS_SUBSCRIPTIONS: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.ROOT,
  AVAILABLE_PLANS: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.AVAILABLE_PLANS,
  SUBSCRIPTIONS: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.SUBSCRIPTIONS,
  PAYMENTS: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.PAYMENTS,
  INVOICES: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.INVOICES,
  BILLING_DETAILS: ADMINISTRATION_PLANS_SUBSCRIPTIONS_ROUTES.BILLING_DETAILS,

  FACILITY_SETTINGS: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.ROOT,
  FACILITY_IDENTITY: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.FACILITY_IDENTITY,
  OPERATIONAL_POLICIES: ADMINISTRATION_FACILITY_SETTINGS_ROUTES.OPERATIONAL_POLICIES,
} as const;
